== BUGS ==

- l'étape 'duplication-manuscrit' de type 'copy-file' tourne en rond lorsque le manuscrit vient d'être défini
  peut-être comme si "${manuscrit-path}" était mal défini. 
  Recommencer maintenant que j'ai mis l'identifiant entre guillemets qui ne doivent pourtant pas jouer…
  LE BUG : EN fait, ça doit venir du fait que l'id n'était pas défini… Mais alors, il faut voir POURQUOI l'erreur de  l'id manquant n'est pas signalé
  IDÉE : parce que la ligne vide contient en vérité "  " et donc que les deux étapes sont "compilées"
  ==> FAIRE VRAIMENT DES LIGNES VIDES 

== Todo En cours

- En cas d'erreur, utiliser le panneau des erreurs (essayer avec l'update de la documentation)

== Todo list ==

- bouton commun pour ouvrir les données du projet (en indiquant "prudence")
- pour le type 'select', il faudrait un select customisé (le même que dans Eventer) avec possibilité de filtrer les valeurs.

- En cas d'erreur (tout le temps) : utiliser la fenêtre des script-services
- fenêtre des erreurs : ne pas utiliser le break:n'importe où qui coupe les mots, mais faire un test sur les longues parties sans espace/coupures possible


- pouvoir récupérer les tâches de todoist
- pouvoir ajouter des tâches à todoist

  
- utiliser des icônes SVG simples (pour l'interface)
- pouvoir éditer le fichier d'un script perso

== Idées d'autres services ==

- git init (tout le flux, juste en donnant le nom du repo sur Github)
- Lancer un serveur de dev (`npm run dev`, `rails server`...) — terminal dédié, pas juste "jouer un script"
- Ouvrir le repo Git (statut, ou `git pull`/`push`)
- Ouvrir l'URL locale du projet dans le navigateur