== BUGS ==

cf. gh

- Test à faire : sélection d'un projet → relance → projet sélectionné → le retirer → relancer → pas de bug, et last_project de App a été vidé

== Todo En cours

- Obtenir la liste des "todo" provenant de github (gh)
  - choisir le label (même mécanisme que pour issue create)
  - commande gh issue list -l <label> envoyé au projet
  - remontée et formatage du résultat.

== Todo list ==

- faire passer tous les tests
- ajouter les tests pour toutes les fonctionnalités
- liste de… (gh)
- github : créer les labels standard (liste de labels à cocher — option 'select_all' dans le paramètre, avec multi: true)
- un type 'services' qui permet de définir la liste des services à afficher dans les panneaux en fonction du projet. Certains utilisateurs, par exemple, ne se serviront jamais de git.
- service git pour ouvrir Github distant
  
== Réflexions ==

=== Réflexion sur la liste des isssues ===

Ça concerne le service 'git-issue-list'. Il me semble que c'est un service un peu différent dans le sens où il doit accomplir une action avant et après.
Non, en fait, c'est juste le select qui va appeler une fonction pour établir la liste des issues à remonter.
Sauf quand même qu'il y a encore une opération derrière

== Idées d'autres services ==

== Autres versions ==

- surveiller des mots ? (rêve que j'ai fait : :error quand on est en train d'écrire (ou pas : la page pourrait surveille ":" ou ":[a-z]" et passer en mode pour insérer quelque chose)). :note, :idee, :error, 
  Mais comment les taper ? une console qui permetttrait par exemple de faire ':error Ceci est une grave erreur' qui serait aussi transformé en service gh-create-issue de type 'bug' ?
  Commandes possible :
    :open     Ouvrir le projet
    :versionne minor  Versionner le fichier désigné
    :<custom> associé à service 
    :run Actualiser le code       Joue le service appelé "Actualiser le code" dans le projet
    :run item claude            Fonctionne en toute casse
    Mais est-ce que c'est vraiment intéressant alors que prendre la souris serait plus rapide ?
