== BUGS ==

- (pas vraiment un bug) Il faut trouver un autre moyen de faire apparaitre les services startup. Moyen à adopter : 
  > au survol, on n'affiche plus la boite des services. On affiche un message "Maj+clic pour montrer les services"
  > + nouvelle fonction on maj+click pour afficher les services startup
  > peut-être : ne plus les mettre en position:absolute, que ça ouvre un espace avec les services bien visibles
  > + on referme en refaisant maj+clic

== Todo En cours  

- faire passer tous les tests

== Todo list ==

- pouvoir récupérer les tâches de todoist
- pouvoir ajouter des tâches à todoist

  
- utiliser des icônes SVG simples (pour l'interface)
- pouvoir éditer le fichier d'un script perso

== Idées d'autres services ==

- git init (tout le flux, juste en donnant le nom du repo sur Github)
- Lancer un serveur de dev (`npm run dev`, `rails server`...) — terminal dédié, pas juste "jouer un script"
- Ouvrir le repo Git (statut, ou `git pull`/`push`)
- Ouvrir l'URL locale du projet dans le navigateur