== BUGS ==

- quand on utilise project.icon dans les Notifier, il faut le chemin absolu
- quand une tâche est marquée modifiée, il faut voir si elle n'a pas de reminder, car
  il faudrait alors le retirer
  Cela arrive lorsque l'on exécute une tâche avant l'heure. Elle a donc été programmée et on la retire avant.
  Trois solutions : 
    1/ avant d'exec un reminder, on checke si la tâche existe toujours
    2/ on supprime le reminder au moment du retrait de la tâche (moins sûr)
    3/ après être remonté de l'update des tasks, on vérifie la concordance avec les reminders
      (qui de toutes façons peuvent avoir été modifiés)
  FAIRE UN TEST POUR ÇA
  AUTRE TEST : Une tâche programmée pour dans le futur mise à un futur plus proche
- quand un projet est réactivé de force parce qu'il a des tâches à l'heure, il faut régler son badge

- Problème d'icône dans la documentation : fonctionne hors app, pas avec l'app

- Problème de définition dans le projet Board
    common_services_data:
      open-a-file:
      - file:///Users/philippeperret/Programmes/Board/_dev/Manuel/Manuel.html
    BUG : 'open-a-file' peut être malheureusement utilisé pour beaucoup d'autres
          choses — attention, il s'agit peut-être d'un scorie. Quand on traitera ce bug,
          commencer par supprimer cette donnée pour voir qui l'utilise (certainement
          l'ouverture de la documentation)


== Todo En cours

- Pouvoir modifier une tâche

== Todo list ==

- pour le type 'select', il faudrait un select customisé (le même que dans Eventer) avec possibilité de filtrer les valeurs.
  
== Idées d'autres services ==

- git init (tout le flux, juste en donnant le nom du repo sur Github)
- Lancer un serveur de dev (`npm run dev`, `rails server`...) — terminal dédié, pas juste "jouer un script"
- Ouvrir le repo Git (statut, ou `git pull`/`push`)
- Ouvrir l'URL locale du projet dans le navigateur