== BUGS ==

- Problème d'icône dans la documentation : fonctionne hors app, pas avec l'app
- Problème de définition dans le projet Board
    common_services_data:
      open-a-file:
      - file:///Users/philippeperret/Programmes/Board/_dev/Manuel/Manuel.html
    BUG : 'open-a-file' peut être malheureusement utilisé pour beaucoup d'autres
          choses — attention, il s'agit peut-être d'un scorie. Quand on traitera ce bug,
          commencer par supprimer cette donnée pour voir qui l'utilise (certainement
          l'ouverture de la documentation)


== Todo En cours

- charger progressivement les tâches des projets, ne pas les balancer tous d'un coup
  => faire une méthode progressive sur chaque projet, un forEachAsync

== Todo list ==

- quand un projet même "caché" a une alerte, l'afficher : déplier le projet sur le bureau + notification
- fin d'horloge : notification aussi.
- pour le type 'select', il faudrait un select customisé (le même que dans Eventer) avec possibilité de filtrer les valeurs.
- pouvoir récupérer les tâches de todoist
- pouvoir ajouter des tâches à todoist

  
- utiliser des icônes SVG simples (pour l'interface)
- pouvoir éditer le fichier d'un script perso

== Idées d'autres services ==

- git init (tout le flux, juste en donnant le nom du repo sur Github)
- Lancer un serveur de dev (`npm run dev`, `rails server`...) — terminal dédié, pas juste "jouer un script"
- Ouvrir le repo Git (statut, ou `git pull`/`push`)
- Ouvrir l'URL locale du projet dans le navigateur