== BUGS ==

- quand un projet est réactivé de force parce qu'il a des tâches à l'heure, il faut régler son badge

- Problème d'icône dans la documentation : fonctionne hors app, pas avec l'app

- Problème de définition dans le projet Board
    common_services_data:
      open-a-file:
      - file:///Users/philippeperret/Programmes/Board/_dev/Manuel/Manuel.html
    BUG : 'open-a-file' peut être malheureusement utilisé pour beaucoup d'autres
          choses — attention, il s'agit peut-être d'un scorie. Quand on traitera ce bug,
          commencer par supprimer cette donnée pour voir qui l'utilise (certainement
          l'ouverture de la documentation)


== Todo En cours


== Todo list ==

- pour le type 'select', il faudrait un select customisé (le même que dans Eventer) avec possibilité de filtrer les valeurs.
  
== Idées d'autres services ==

- git init (tout le flux, juste en donnant le nom du repo sur Github)
- Lancer un serveur de dev (`npm run dev`, `rails server`...) — terminal dédié, pas juste "jouer un script"
- Ouvrir le repo Git (statut, ou `git pull`/`push`)
- Ouvrir l'URL locale du projet dans le navigateur