== BUGS ==

- Il faut pouvoir dire à un rappel que c'est bon, on a démarré la tâche

- les erreurs mineures (footer) quand un panneau est ouvert, ne se lisent pas
  essayer en essayant de modifier une tâche sans en avoir sélectionné une

- Problème d'icône dans la documentation : fonctionne hors app, pas avec l'app

== Todo En cours

== Todo list ==

- pouvoir déplacer en glissant le panneau des services (pour le rapproche d'un projet)
- Il faudrait essayer de rationnaliser les données Projet, si c'est possible
  Mais est-ce vraiment nécessaire ?
  On a : 
    - les données racines (title, date création, temps de travail, etc.)
    - les données de services affectés (services startup et others)
    - les données des autres services
      - données des script-services 
      - services communs non affectés
- Pour les rappels de tâches à l'heure, les mettre en warning

- Panneaux : il faudrait fermer le panneau avant de faire l'opération (surtout gênant quand on clique sur "Confirmer" pour les tâches et que ça met un temps à disparaitre)
  En fait : clic → Fermer fenêtre → Sablier → Confirmation fin

- pouvoir mettre une note gh (github) du type voulu
- pour le type 'select', il faudrait un select customisé (le même que dans Eventer) avec possibilité de filtrer les valeurs.
  
== Idées d'autres services ==

- git init (tout le flux, juste en donnant le nom du repo sur Github)
- Lancer un serveur de dev (`npm run dev`, `rails server`...) — terminal dédié, pas juste "jouer un script"
- Ouvrir le repo Git (statut, ou `git pull`/`push`)
- Ouvrir l'URL locale du projet dans le navigateur