== Prise en main ==

Après avoir lancé l'application, on se retrouve devant un tableau de bord qui permet d'ajouter ses projets en définissant pour chacun d'eux les <<services>> dont on a besoin.

Chaque projet se présente sous forme d'une carte (un peu comme dans Trello) qui possède en titre le nom du projet et contient la liste des différents services qui lui ont été affectés.

~~~
“Affecter des services” est l'expression consacrée pour dire qu'on utilise des <<services>> pour un projet.
~~~

Chaque carte est composée de trois parties : 

- l'entête, avec le titre du projet et quelques informations le concernant,
- une partie supérieure contient tous les services qui seront activés lorsque l'on cliquera sur le bouton “{start-work}”,
- une partie inférieure contient les boutons qu'on peut utiliser à l'occasion pour des traitements particuliers.

----
---------------------------————
|       TITRE PROJET          |
|                       infos |
|-------------------------————|
|   Service 1                 |
|   Service 2                 |
|                             |
|    ---------------------    |
|   | Démarrer le travail |   |
|    ---------------------    |
|_____________________________|
|   Autre service 1           |
|   Autre service 2           |
|   ...                       |
|                             |
–––––––––––––––––––––––––––––––
----

=== Panneau de nouveau projet ===

Quand on clique sur le "+" qui se trouve à gauche en bas de l'interface, un panneau s'ouvre pour définir le nouveau projet. 

La partie supérieure permet d'entrer les informations sur le projet : 

- lui donner un titre,
- indiquer son dossier de référence (un projet doit toujours avoir un dossier),

La partie inférieure permet de choisir les <<services>> par simple glisser-déposer.

Exemple : pour le service “Ouvrir dans le Finder”, une fois qu'on l'a glissé sur le projet, une fenêtre s'ouvre, demandant d'ouvrir la fenêtre dans le Finder, de la positionner et de la mettre ans la vue désirée (colonnes, lignes, etc.). Une fois que c'est fait, on clique sur “OK” et l'application va automatiquement prendre les informations sur la fenêtre au premier plan dans le finder.
