[[scripts-services, les scripts-services]]
=== Les scripts-services ===

Les _scripts-services_ ouvrent définitivement la voie de l'infini pour définir les services d'un projet. Ils permettent de **composer soi-même un service** en exploitant toutes les ressources de l'application.

Mais tout pouvoir puissant implique des responsabilités à ses propotions.

[[script-services-steps]]
==== Une suite d'étapes ====

Un _script-service_ est un fichier YAML qui décrit les étapes du service. Concrètement, cela signifie que le fichier comporte des tirets pour délimiter chaque étape.

[code, yaml]
----
---
- name: Première étape

- name: Deuxième étape

- name: Troisième étape

# etc.
----

Pour illustrer l'explication qui va suivre, nous allons imaginer être une autrice ou un auteur et programmer un service de suivi d'envoi de manuscrits à des maisons d'édition, pour ne pas avoir à répéter un même processus des dizaines de fois, ce qui peut être pénible si l'on écrit un roman, voire plus, par an.

En apparence, ce service doit être simple : 

- création d'un dossier pour l'éditeur ou l'éditrice
- copier du manuscrit à envoyer
- création d'un fichier avec l'adresse et le téléphone de l'édition
- enregistrement d'un historique des envois, pour se souvenir de quand le manuscrit a été envoyé.

Notre fichier YAML comprendra donc ces étapes, assurément : 

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"

- name: "Copie du manuscrit envoyé"

- name: "Fichier information éditeur

- name: "Enregistrement envoi dans l'historique"

----

Noter que le `name` des étapes est optionnel, mais pour la clarté, il vaut mieux le définir.

En revanche, chaque étape doit impérativement avoir un identifiant (`ìd`). C'est une valeur ne comportant que des lettres minuscules, des chiffres, des tirets et des traits plats. Si l'identifiant contient des tirets, il doit obligatoirement être entre guillemets.

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"
  id: "creer-dossier-editeur"

- name: "Copie du manuscrit envoyé"
  id: copier_manuscrit

- name: "Fichier information éditeur
  id: informations_editeur

- name: "Enregistrement envoi dans l'historique"
  id: historique

----

==== Erreurs classiques ====

Vous trouverez dans cette partie une liste des erreurs classique lorsqu'on établit ses étapes.

|====
| **Manifestation** | **Erreur** 
|====

==== Commun à tous les types ====

[col="1,3"]
|====
| `if`        | Pour une <<conditional-step>>.
| `id`        | Une étape toi toujours avec un identifiant, unique, contenant seulement des minuscule, des chiffres et des tirets.
| `type`      | Une étape doit toujours définir <<script-service-types, un type>>
| `q`         | Le message dans une boite de dialogue, en fonction du type attendu.
| `title`     | Le titre de la boite de dialogue, en fonction du type attendu.
|====

[[conditional-step, étape conditionelle]]
===== Étape conditionnelle =====

On utile le paramètre `if` pour définir une étape conditionnelle.

La valeur de `if` doit alors être composée de 3 expressions séparées par une espace, la première étant la valeur a comparée, la 3^e^ la valeur de comparaison et la 2^e^ l'opérateur.

----
if: "expression operateur expected"
----

`expression` est le plus souvent un identifiant d'étape exprimé par `${<id etape>}`. On prendra alors la valeur de cette étape pour la comparer à `expected`.

`operateur` peut être `==` ou `=`, `!=` ou `≠`, `>`, `<`.

`Expected` peut-être n'importe quelle valeur, en sachant que "null", "undefined", "empty" seront évalués. +
Quand le type est `select` et que `create` est à true (ou nom du bouton "Autre…"), autorisant la création d'une nouvelle valeur, `expected` doit alors être ''. Par exemple : 

----
- id: 'value-selected-or-created'
  name: 'valeur à sélectionner ou créer'
  type: 'select'
  create: true
  
- if: "${value-selected-or-created} == ''
  type: 'string'
  title: "Nouvelle valeur
  q: "Donnez la nouvelle valeur.
  
----


[[evaluate, évaluation]]
==== Contenu évaluable ====

Dans les étapes, un contenu _évaluable_ est un contenu qui se sert de la valeur d'une autre étape pour être défini.

Ce contenu s'indique par :

----
${step-id}          # Valeur de l'étape d'id +step-id+
${step-id}[prop]    # Si la valeur de l'étape *step-id+ est un objet, on
                    # prend la propriété +prop+ de cet objet.
${step-id}.prop     # Idem, sous une autre forme
----

Par exemple, on récupère un dossier et on s'en sert ensuite dans les étapes suivantes :

----
---
# On demande à l'utilisateur de choisir un dossier
- id: 'dossier'
  type: 'choose-folder'
  q: "Choisissez le dossier puis “OK”."

# On crée un fichier dans ce dossier.
- id: 'un-fichier-dans-le-dossier'
  type: 'add-to-file'
  # Le fichier estimé dans le dossier
  path: "${dossier}/mon_fichier.md"
  # Le contenu aussi peut s'en servir
  content: "Le contenu de mon fichier dans le dossier ${dossier}.

----

[[script-service-types, les types d'étape]]
==== Les types d'étapes (step) ====

[[script-service-type-add-to-file]]
===== Ajouter du contenu à  un fichier =====

Ce type d'étape permet d'ajouter du contenu à un fichier.

----
---
- id: 'id-etape'
  type: 'add-to-file'
  path: "/chemin/vers/fichier
  content: ""
  after: "..."
  before: "..."
  where: [{after:...}, {before:...}, ...]
----

[col="1,1, 3"]
|====
| `path`    2+| Chemin d'accès au fichier
|             | Chemin absolu     | Aucune substitution nécessaire
|             | Chemin relatif    | Doit se trouver dans le dossier du projet et commencer par "./"
|             | Chemin évaluable  | Se sert de la valeur d'autres étapes
| `content` 2+| Le contenu à écrire dans le fichier. Il peut être brut ou <<evaluate, évaluable>>
| `after`   2+| Indique après quoi il faut mettre le contenu.
|             | String    | Ça peut être l'expression en chaine, p.e. "ce mot"
|             | Exp. reg. | Ou une expression régulière. P.e. "(?!un ) voisin", pour mettre après "le voisin" mais pas "un voisin). Ces expressions demande de l'expérience.
| `before`  2+| Indique avant quoi il faut mettre le contenu. Mêmes formats que pour `after`.
| `where`   2+| Alors que `after` et `before` ne permettent qu'une localisation à un paramètre, `where` permet de définir très précisément où mettre le contenu. Mais cette définition est très sensible.
|           2+| Voilà un exemple (absurde mais simple) : nous voulons ajouter ", cuisine" dans le contenu d'un fichier qui est pour le moment : "Je dois mettre au grenier un mot entre chambre et grenier." +
Nous utilisons pour ce faire : `where = [{after: "chambre"}, {before: " et grenier"}]
|           2+| De façon plus réaliste, sur cette base, on peut imaginer que le fichier contient des balises comme par exemple "/* -- debut data -- */" et "/* -- fin data -- */". Pour ajouter une donnée, on peut donc faire : +
`where = [{after: "/* -- debut data -- */\n"}, {before: "\n/* -- fin data -- */"}] +
Noter les retours de chariot marqués par "\n".
|====


[[script-service-type-save-data]]
===== Save-data =====

Permet d'enregistrer une donnée à la volée.

[cols="1,1,2"]
|====
| `type`    2+| `save-data`
| `id`      2+| Identifiant de l'étape.
| `values`  2+| Les valeurs à enregistrer ou les identifiants
|             | valeurs brutes | Sans `prefix` les valeurs sont des valeurs brutes
|             | avec `prefix`  | Les clés d'un objet à reconstituer qui serviront aussi à obtenir les valeurs depuis les étapes d'identifiant `<prefix>-<clé>`
| `prefix`  2+| Préfixe à utiliser pour rassembler
|====

Par exemple, si l'on doit reconstituer un objet "Livre" qui possède les clés `titre`, `auteur` et `annee`, on créera les étapes id = `livre-titre`, id= `livre-auteur` et id = `livre-annee` et l'on définir les données de l'étape par :

----
---
- id: "livre-titre"
  type: "string"
  q: "Titre du livre"

- id: "livre-auteur"
  type: "string"
  q: "Auteur du livre
  
- id: "livre-annee"
  type: "integer"
  q: "Année de publication

- id: 'save-the-book'
  type: 'save-data'
  values: ['titre', 'auteur', 'annee']
  prefix: 'livre
----



[[script-service-type-set]]
===== Set =====

Permet de **définir explicitement le `step.value` d'une étape** ou de l'étape courante (pour définir une variable utile sur tout le service). Cela arrive par exemple lorsque pour un `select` on peut créer une nouvelle valeur.

[cols="1,1,2"]
|====
| `type`      2+| `set`
| `id`        2+| Identifiant obligatoire
| `step`      2+| Identifiant de l'étape dont il faut définir la valeur +
Si non défini, c'est l'étape elle-même dont on définira la valeur
| `value`     2+| Valeur à donner à `value` de l'étape
>|          soit| Valeur explicite | Donnée telle quelle 
>|          soit| Valeur d'étape   | ${<id etape>}
|====

[[script-service-type-select]]
===== Select =====

[cols="1,1,2"]
|====
| `id`      2+| Identifiant obligatoire
| `type`    2+| **`select`**
| `create`  2+| `true` ou le nom du bouton "Nouveau…" si on doit pouvoir créer une nouvelle valeur +
                Ça donne la valeur 'autre' à cette étape (cf. la suite).
| `values`  2+| Les valeurs parmi lesquelles ont peut choisir
|             | string          | le chemin à un fichier contenant les valeurs +
La valeur sera évaluée, donc peut-être définie par "${<id étape>}"
>|        ou  | array of string | Liste de valeurs simples (['poire', 'melon'])
>|        ou  | array of array  | Liste de doubles valeurs [[value, title], ...] 
|====

Si _`create`_ est true (ou nom du bouton "Autre…"), on peut créer une valeur de toute pièce. Cette création se fait, en toute logique, au cours des étapes suivante. Ces étapes de définition vont toutes commencer par :

----
- if: "${<identifiant étape>} = ''"
----

Plusieurs étapes de ce type peuvent s'enchainer pour obtenir toutes les valeurs pour le type de données fournie.

TIP: Cette valeur est souvent réaffectée à l'étape `select` grâce à un type `set`. Voilà la séquence classique :

----
---
- id: 'le-choix'
  type: select
  values: [1, 2, 3]
  q: "Choisissez un chiffre
  create: "Autre chiffre…" # pour permettre de choisir un autre chiffre

# Comme le choix "Autre…" a été choisi, on propose
# un dialogue pour entrer une autre valeur
- if: "${le-choix} == ''"
  id: 'autre-chiffre'
  type: string
  q: "Quel autre chiffre ?"
  
# Maintenant qu'on a la valeur, on la place dans l'étape
# 'le-choix' car c'est elle qui sera référencée dans la suite
- if "${le-choix} == ''"
  type:   set
  step:   "le-choix"            # -- l'étape qu'il faut redéfinir
  value:  "${autre-chiffre}"    # -- la valeur qu'il faut lui affecter

# À partir d'ici, l'étape ${le-choix} contient la valeur voulue,
# qu'elle est été prise dans le menu ou définie explicitement.

----

[[script-service-file-values]]
==== Données dans un fichier ====

On peut tirer des données d'un grand nombre de fichiers. La seule exigence est que la donnée remontée ait le même type que la donnée attendue (string, array, array de strings, etc.).

Cela concerne donc en tout premier lieu les fichiers YAML, JSON et CSV, mais on peut également trouver tout fichier éditable (ruby, bash, python…) qui pourra retourner une donnée de ce type. Mais dans ce cas, il est impératif que ce fichier soit EXÉCUTABLE (`chmod +x fichier`) et qu'il retourne un données ÉVALUABLE PAR JSON, sauf si c'est une valeur scalaire (string, integer…).


[cols="1,3"]
|====
| `type` | `get-data`
| `base` | Chemin d'accès au fichier contenant les données (évaluable)
| `key`  | Si précisé, c'est la clé à prendre
|====

Deux sortes de données peuvent être remontées :

- une table (dict) dont une clé correspondra à `key`,
- une liste d'objet (array) qui devra contenir un élément répondant à `id = key`.

===== Set Project Data =====

Type d'étape qui permet de définir une donnée de projet.

[cols="1,3"]
|====
| `type` | `get-project-data`
| `id` | Identifiant.
| `project_key` | La clé dans les extra-données du projet.
| `value`       | La valeur à donner à cette clé. Elle vient, normalement, d'une autre étape ayant permis de la définir. Voir la <<sequence-project-data>>.
|====

===== Get Project Data =====

Type d'étape qui permet de récupérer une donnée de projet.

[cols="1,3"]
|====
| `type` | `get-project-data`
| `id` | Identifiant. Mais pour ce type d'étape, il est particulier : il doit porter le nom de la donnée du projet, impérativement, pour pouvoir être redéfini si la donnée manque.
| `project_key` | La clé dans les extra-données du projet.
|====

Voir la <<sequence-project-data>>.

[[sequence-project-data]]
**Exemple de séquence de définition de donnée de projet**

----
---
# On essaie de prendre le chemin au manuscrit
# dans les données du projet.
- id: 'manuscrit-path'
  type: 'get-project-data'

# Comme la donnée est nulle au départ, on va demande
# de choisir le manuscrit.
- if: "${manuscript-path} == null"
  id: "definition-manuscrit"
  type: 'select-file'
  q: "Choisissez le manuscrit dans le Finder puis “OK”."
  
- if: "${manuscript-path} == null"
  id: "set-project-manuscrit"
  type: 'set-project-data'
  project_key: 'manuscrit-path'  # la clé
  value: ${definition-manuscrit} # pour récupérer le path
  
- type: 'copy-file'
  source: "${manuscrit-path}"  # Aura été renseigné
----