[[scripts-services, les scripts-services]]
== Les scripts-services ==

Les _scripts-services_ offrent des possibilités infinies pour gérer ses projets. Ils permettent de **composer soi-même un service complexe** en exploitant toutes les ressources de l'application. Le tout premier script-service composé au moment de l'implémentation de cette application a permis de produire, avec un simple clic sur un bouton un service qui accomplissait les tâches suivantes : 

|====
| Il demande de choisir une maison d'édition (ME)
| Ou permet d'en créer une nouvelle
| Il crée un dossier d'envoi pour cette ME, dans le dossier `envois` du projet,
| Il demande de choisir le manuscript courant s'il n'était pas déjà défini
| Il duplique le manuscrit dans le dossier de la ME le manuscript courant à envoyer +
_(je préfère dupliquer le fichier pour être toujours certain de savoir ce que j'ai envoyé)_
| Il crée un fichier avec l'adresse et le téléphone de la ME.
| Il demande la date exacte d'envoi (aujourd'hui, demain ou une date précise).
| Il incrémente l'historique des envois en y ajoutant cet envoi, avec la date (différée ou non).
|====

Tout cela, nous le redisons : par un simple clique sur un bouton.

ATTENTION: Tout pouvoir puissant, cependant, implique des responsabilités proportionnelles, comme nous le verrons. Il est donc conseillé d'avancer doucement dans la conception de ces _scripts-services_ jusqu'à se sentir suffisamment à l'aise pour en composer des compliqués.

[[scserv-types]]
=== Liste complète des types assemblables ===

_Une fois familiarisé(e) avec les scripts-services, vous pouvez utiliser la table ci-dessous pour un accès rapide aux différents types de service_

[cols="1,3, 1"]
|====
| **Type de service**               | **Objet**                                 | **Paramètres propres**
| <<scserv-type-set>>               | Pour définir la valeur d'une étape.       | `step` + `value`
| <<scserv-type-select>>            | Sélection une valeur parmi un ensemble de
                                      valeur ou en créer une nouvelle.          | `values`, `create`
| <<scserv-type-select-file>>       | Sélection d'un fichier (dans le Finder).  | 
| <<scserv-type-create-file>>       | Création d'un fichier.                    | `path` + `content`
| <<scserv-type-add-to-file>>       | Ajout s'un contenu à un fichier.          | `after`, `before` + `where`
| <<scserv-type-get-data>>          | Obtention de données complexes 
                                      (array d'objets) depuis un fichier.       | `path`, `data_id`
| <<scserv-type-save-data>>         | Enregistrement de données complexes.      | `prefix`, `keys`
| <<scserv-type-choose-folder>>     | Sélection d'un dossier (dans le Finder).  |
| <<scserv-type-create-folder>>     | Création d'un dossier.                    | `path`
| <<scserv-type-copy-file>>         | Copie d'un fichier.                       |
| <<scserv-type-set-project-data>>  | Pour définir une propriété pour le projet.| `step` + `value` + `project_key`
| <<scserv-type-get-project-data>>  | Pour obtenir une propriété du projet.     | `id` = prop extradata
| <<scserv-type-translate>> | Pour transformer une marqueur selon un
                              certain format.                           | `value` + `format`
| <<scserv-type-string>>            | Obtenir une valeur string.                | 
| <<scserv-type-text>>              | Obtenir une valeur texte (multi lignes).  |
| <<scserv-type-phone>>             | Obtenir un numéro de téléphone.           |
|====


[[script-services-steps]]
=== Une suite d'étapes ===

**Un _script-service_ est un fichier YAML qui décrit la suite procédurale des étapes du service**. Concrètement, cela signifie que le fichier comporte des tirets pour délimiter chaque étape.

[code, yaml]
----
---
- name: Première étape
  id: etape-1

- name: Deuxième étape
  id: etape-2

- name: Troisième étape
  id: etape-3

# etc.
----


[[scserv-tuto-create-script-service, création d'un script-service]]
=== Tutoriel : création d'un script-service ===

Pour illustrer l'explication qui va suivre, nous allons imaginer être une autrice ou un auteur et programmer un service de suivi d'envoi de manuscrits à des maisons d'édition comme celui présenté plus haut, pour ne pas avoir à répéter les mêmes actions des dizaines de fois, ce qui peut être pénible si l'on écrit un roman, voire plus, par an.

En apparence, ce service doit être simple : 

- création d'un dossier pour l'éditeur ou l'éditrice
- copier du manuscrit à envoyer
- création d'un fichier avec l'adresse et le téléphone de l'édition
- enregistrement d'un historique des envois, pour se souvenir de quand le manuscrit a été envoyé.

Notre fichier YAML comprendra donc ces étapes, assurément : 

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"

- name: "Copie du manuscrit envoyé"

- name: "Fichier information éditeur

- name: "Enregistrement envoi dans l'historique"

----

Noter que le `name` des étapes est optionnel, mais pour la clarté, il vaut mieux le définir.

En revanche, chaque étape doit impérativement avoir un identifiant (`ìd`). C'est une valeur ne comportant que des lettres minuscules, des chiffres, des tirets et des traits plats.

Nous verrons plus tard l'importance des identifiants, qui deviennent de véritables variables contenant une valeur dynamique.

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"
  id: creation-du-dossier-envoi

- name: "Copie du manuscrit envoyé"
  id: copier_manuscrit

- name: "Fichier information éditeur
  id: informations_editeur

- name: "Enregistrement envoi dans l'historique"
  id: historique

----
      
Nous déterminons l'action de l'étape en définissant son type. À titre de rappel, ils sont tous définis <<scserv-types, ici>>.  

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"
  id:   creation-du-dossier-envoi
  type: create-folder

- name: "Copie du manuscrit envoyé"
  id: copier_manuscrit
  type: copy-file

- name: "Fichier information éditeur
  id: informations_editeur
  type: create-file

- name: "Enregistrement envoi dans l'historique"
  id: historique
  type: add-to-file
----

Vous trouverez tout ce dont chaque type a besoin en rejoignant la section idoine depuis le <<scserv-types, tableau des types>>.
    
Nous allons commencer par `create-folder` qui a simplement besoin du chemin d'accès. Ce dossier sera créé dans le projet, dans un dossier général `envois` avec l'identifiant de l'éditeur. Nous inscrivons donc : 

----
---
- name: "Création du dossier de l'éditeur"
  id: creation-du-dossier-envoi
  type: create-folder
  path: "./envois/${editeur-id}"
----

Remarquez dès à présent la variable **`${editeur-id}`** qui contiendra donc l'identifiant de l'éditeur. Cette variable fait directement référence à la valeur (`value`) d'une étape précédente. Nous ne la ferons pas tout de suite, mais nous la notons déjà pour ne pas l'oublier.

----
---
- id: editeur-id
  name: "Identifiant de l'éditeur
  # à compléter

- name: "Création du dossier de l'éditeur"
  id: creation-du-dossier-envoi
  type: create-folder
  path: "./envois/${editeur-id}"
----

Noter également les chemins qui commencent par `./` et font donc référence au dossier du projet.

Nous devons ensuite copier le manuscrit avec le type `copy-file`. Pour ce type, nous devons simplement indiquer la source (le fichier à dupliquer) et la destination. Soit le dossier dans lequel mettre le fichier, qui gardera le même nom, soit le chemin complet avec le nouveau nom du fichier. Ici, nous gardons le même nom, donc : 

----
- name: "Copie du manuscrit envoyé"
  id: copier_manuscrit
  type: copy-file
  source: "${manuscrit-path}"
  dest: "./envois/${editeur-id}"
----

Notez la nouvelle variable **`${manuscrit-path}`**, entre guillemets, qui, bien entendu, connait le chemin d'accès au fichier. Ici aussi, nous devrons régler cette variable, donc cette étape, plus tard : 

----
- id: manuscrit-path
  name: "Chemin d'accès au manuscrit"
  
- name: "Copie du manuscrit envoyé"
  id: copier_manuscrit
  type: copy-file
  source: "${manuscrit-path}"
  dest: "./envois/${editeur-id}"
----

Passons au fichier qui va contenir l'adresse et le téléphone de l'éditeur (juste par facilité car je pourrais aussi programmer un petit outil qui retrouve facilement ces informations en les prenant dans la base au moment où nous en avons besoin.)

Pour créer un fichier, nous avons besoin de son chemin d'accès (relatif au projet ou absolu) et de son contenu. Nous les indiquons avec les propriétés `content` (contenu) et `path` (chemin d'accès) :

----
- name: "Fichier information éditeur
  id: informations_editeur
  type: create-file
  content: "${data-editor}.adresse\n\n${data-editor}.phone"
  path:   "./envois/${editeur-id}/infos.md"
----

Vous devez déjà bien comprendre le `path` : nous allons mettre ce fichier dans le dossier créé tout à l'heure. Ce fichier s'appellera `infos.md`.

Vous voyez que le contenu du fichier peut être complexe. Ici, nous faisons référence non pas à une valeur simple d'étape (`data-editor`) mais à une _propriété d'objet_. Un _objet_, c'est une chose informatique quelconque qui contient des propriétés. L'objet `data-editor`, que nous définirons plus tard, est un objet de cette forme : 

----
data-editor
  id:       Son identifiant
  name:     Son nom
  adresse:  Son adresse
  phone:    Son téléphone
  email:    Son adresse mail
----

On peut imaginer évidemment autant de propriétés que l'on veut.

On y fait référence ensuite, simplement, en utilisant soit `objet.propiété` soit `objet[propriété]`, les deux donnent le même résultat (ce sont des syntaxes classiques pour les programmeurs).

Donc, ici, le contenu : 

----
"${data-editor}.adresse\n\n${data-editor}.phone"
----

… signifie que nous allons prendre l'`adresse` de l'éditeur choisir, la faire suivre de deux retours à la ligne (`\n`), puis que nous allons mettre son numéro de téléphone.

NOTE: Noter que je mets ces deux informations car ce sont celles dont j'ai besoin pour un envoi. L'adresse pour le lieu de l'expédition et le téléphone pour le suivi.

Notons que là aussi il nous faudra revenir sur une information : `data-editor` qui sera là aussi, _forcément_, la valeur d'une étape.

----
- id: data-editor
  name: "Données complète de l'éditeur choisi"

- name: "Fichier information éditeur
  id: informations_editeur
  type: create-file
  content: "${data-editor}.adresse\n\n${data-editor}.phone"
  path:   "./envois/${editeur-id}/infos.md"
----

Il nous reste à régler le texte ajoute à l'historique d'envoi. Pour ça, nous avons besoin de trois choses : 

- le chemin d'accès au fichier,
- le contenu à ajouter,
- l'endroit où ce contenu doit être ajouté.

Nous les indiquons avec les propriétés `path` (chemin d'accès), `content` (contenu) et `before` (avant) pour indiquer l'endroit :

----
- name: "Enregistrement envoi dans l'historique"
  id: historique
  type: add-to-file
  before: "\n-"
  path: "./envois/_HISTORIQUE_.md"
  content: "- ${date-histo} Envoi aux éditions ${data-editor}.name\n"  
----

Notez qu'à la place de `before`, on peut utiliser `after` (après) ou `where` (“où”, solution complexe pour indiquer la place exacte, lorsqu'elle n'eest pas simple à définir). Pour ces propriétés, voir le type <<scserv-type-add-to-file>>.

Dans le script réel, j'ai la possibilité de ne pas incrémenter l'historique (par exemple lorsque je veux préparer l'envoi mais que je ne sais pas encore quand je vais pouvoir le faire). Cela va nous permettre d'étudier le type <<scserv-type-select>> et les conditions.

En fait, c'est en demandant la date d'envoi que nous allons savoir ça :

----
- id: 'date-histo'
  type: select
  title: "Date de l'envoi"
  q: "Faut-il ajouter cet envoi à  l'historique des envois ? Et si oui, quelle date faut-il indiquer ?"
  create: 'Autre date…'
  values: [['today', 'Aujourd’hui'], ['demain', "Demain"], ['non', 'Pas encore']]
----

Pour fonctionner, le type <<scserv-type-select>> a besoin de : 

- un titre dans `title` (le titre de la fenêtre de demande),
- une question dans `q` (la question posée à l'utilisateur),
- une liste de valeurs à proposer, dans `values`.

Et comme là je veux me laisser la possibilité de donner ma propre date, j'ajoute : 

- le nom du bouton pour créer une nouvelle valeur dans `create`.

Comme vous pourrez le voir dans la description du type <<scserv-type-select>>, il y a plusieurs manière de donner les valeurs du menu select. Celle-ci : 

----
values: [['today', 'Aujourd’hui'], ['demain', "Demain"], ['non', 'Pas encore']]
----

… affichera les items "Aujourd'hui", "Demain" et "Pas encore" et le texte qui leur est accolé ('today', 'demain', 'non') sera la valeur donnée en fonction du choix. Ici, si je choisis "Pas encore", alors l'étape `date-histo` prendra la valeur `non`. C'est aussi simple que ça. Et donc, il suffit que je vérifie cette condition :

----
- if "${date-histo} = non"
----

Cette condition signifie SI (if en anglais) la valeur de l'étape `date-histo` (`${date-histo}`) vaut (`=`) `non` alors on exécute l'étape. Donc : 

----
# Demande de la date d'envoi (ou pas)
- id: 'date-histo'
  type: select
  title: "Date de l'envoi"
  q: "Faut-il ajouter cet envoi à  l'historique des envois ? Et si oui, quelle date faut-il indiquer ?"
  create: 'Autre date…'
  values: [['today', 'Aujourd’hui'], ['demain', "Demain"], ['non', 'Pas encore']]

# Enregistrement dans l'historique, soumis à condition
- if "${date-histo} = non"
  name: "Enregistrement envoi dans l'historique"
  id: historique
  type: add-to-file
  before: "\n-"
  path: "./envois/_HISTORIQUE_.md"
  content: "- ${date-histo} Envoi aux éditions ${data-editor}.name\n"  
----

Donc, cette étape d'enregistrement dans l'historique ne sera exécutée que si je n'ai pas choisi "Pas encore".

Nous avons donc régler nos quatre étapes décisives, nous allons pouvoir finaliser tout à fait le script-service, mais vous allez voir qu'il nous reste du travail !

Nous allons commencer par demander de choisir un éditeur. C'est encore le type <<scserv-type-select>> qui va être mis à contribution, mais cette fois, à l'aide d'un fichier qui contient tous les éditeurs, un fichier actualisable. Et nous avons aussi la possibilité d'en créer un nouveau, donc nous renseignons le nom du bouton create dans `create`. Cela donne : 

----
- id:     editeur-id
  type:   select
  title: "Choix de la maison d’édition"
  q: "Choisir une maison dans la liste ou en introduire une nouvelle."
  values: "./envois/editeurs.yaml"
  key_value: id
  key_title: name
  create: "Nouvel éditeur…"
----

Nous avons une étape un peu plus complexe ici, au niveau des valeurs… Ce qu'il faut comprendre, c'est que les _objets_ contenus par le fichier `./envois/editeurs.yaml` sont des objets à plusieurs propriétés, comme nous l'avons vu tout à l'heure. Sans autre indication que ce fichier, cette étape du script-service ne saurait pas quelle propriété utiliser. Donc, ici, nous devons lui indiquer `key_value` et `key_title`.

[cols="1,5"]
|====
| `key_value` | Indique la propriété (key) de l'objet qui doit servir de valeur finale (comme le "non" de tout à l'heure).
| `key_title` | Indique la propriété de l'objet qui doit servir de titre à l'item, donc le nom que l'on lira dans le menu.
|====

Donc, dans notre objet éditeur, on prendra la propriété `name` qui servira de titre à l'item de menu, et la propriété `id` sera la valeur, donc la valeur donnée au final à cette étape.

Pour rappel, un objet éditeur dans le fichier `./envois/editeurs.yaml` contient : 

----
---
- id:  gallimard  # Identifiant de l'éditeur
  name: Gallimard # nom
  adresse: |> 
    Son addresse
  phone:    555 01 02 # son téléphone
  ... 
----

Si le bouton "Nouvel éditeur…" est cliqué, la valeur est mise à '' (chaine vide). Dans les étapes suivantes, nous devons donc tester cette valeur pour savoir s'il faut définir ou non un nouvel éditeur. Comme les script-services ne peuvent pas définir plusieurs valeurs en même temps (c'est un principe fondateur), nous devons prendre plusieurs étapes pour définir cet éditeur. Chacune de ces étapes, évidemment, sera conditionnée par : 

----
- if "${editeur-id} = ''"
----

… pour ne pas être jouée si l'éditeur a été choisi dans la liste.

[[scserv-tuto-get-editor-infos]]
Voilà la suite des données à rassembler. Noter que l'identifiant de ces étapes est particulièrement important, comme nous le verrons dans la suite, et qu'il doit être choisi avec soin. 

----
# Demander l'identifiant (non simple)
# Sera mis dans ${new-editor-id}
- if: "${editeur-id} = ''"
  id: "new-editor-id"
  type: string
  title: "Nouvel éditeur"
  q: "Identifiant (ascii) du nouvel éditeur :"

# Demander le vrai nom
# Sera mis dans ${new-editor-name}
- if: "${editeur-id} = ''"
  id: "new-editor-name"
  type: string
  title: "Nouvel éditeur"
  q: "Nom du nouvel éditeur :"

# Demander l'adresse
# Sera mis dans ${new-editor-adresse}
- if: "${editeur-id} = ''"
  id: "new-editor-adresse"
  type: text    # <= noter, un texte multi-lignes
  title: "Nouvel éditeur"
  q: "Adresse physique du nouvel éditeur :"

# Demander le téléphone
# Sera mis dans ${new-editor-phone}
- if: "${editeur-id} = ''"
  id: new-editor-phone
  type: phone
  title: "Nouvel éditeur"
  q: "Numéro de téléphone du nouvel éditeur :"
----

Maintenant que nous avons les informations du nouvel éditeur, nous pouvons les ajouter au fichier. On peut le faire avec le type <<scserv-type-save-data>>.

----
- if: "${editeur-id} = ''"
  id: 'enregistrement-editeur'
  type: "save-data"
  path: "./envois/editeurs.yaml"
  prefix: 'new-editor'
  keys: ['id', 'name', 'adresse', 'phone']
----

Attenton, il faut être attentif pour ce type particulier. Il a besoin de `prefix` et de `keys` pour pouvoir opérer. Le _préfix_ et les _clés_ (keys) s'assemblent pour former les valeurs qui constitueront le nouvel objet : 
  
|====
4+| Nouvel objet 
  | **Key**   | **Composition**     | **Id étape**        | **Valeur étape***
  | `id`      | `<prefix>-id`       | new-editor-id       | "${new-editor-id}"
  | `name`    | `<prefix>-name`     | new-editor-name     | "${new-editor-name}"
  | `adresse` | `<prefix>-adresse`  | new-editor-adresse  | "${new-editor-adresse}"    
  | `phone`   | `<prefix>-phone`    | new-editor-phone    | "${new-editor-phone}"
|====

Vous comprenez maintenant pourquoi le nom des étapes de <<scserv-tuto-get-editor-infos, récolte des informations du nouvel éditeur>> sont tellement importantes.

Un point de détail qui échappera au Padawan mais que maitre Yoda ne manquera pas de noter : c'est la seconde fois que je définis : 

----
path: "./envois/editeurs.yaml"
----

Le problème de ce genre de définition est le suivi : si le fichier change de lieu, je vais avoir plusieurs endroits à changer, si j'y pense ! C'est une faiblesse de conception.

Au lieu de ça, il vaut mieux définir une variable qui contiendra ce chemin d'accès et l'utiliser partout où il devra être utilisé. De cette manière, si je change l'endroit, j'ai une seule modification à faire et toutes les utilisations s'adaptent. Pour ce faire, j'utilise le type <<scserv-type-set>>.

----
---
### Tout en haut du fichier
- id: editors-data
  type: set
  value: "./envois/editeurs.yaml" 
----

Et ensuite, je peux l'utiliser : 

----
- id:     editeur-id
  type:   select
  values: "${editors-data}"  # <= variable
  ...
----

… et puis : 

----
- if: "${editeur-id} = ''"
  id: 'enregistrement-editeur'
  type: "save-data"
  path: "${editors-data}"  # <= variable
  ...
----

Vous n'y penserez peut-être pas tout de suite, mais lorsque vous aurez commis plusieurs fois l'erreur, ça finira pas rentrer. _Long est l'apprentissage du Jedi_

Et maintenant, je ne dois pas oublier une dernière chose : donner à `editeur-id` la valeur qu'il doit avoir, car il est toujours à "" pour le moment. J'utilise là aussi le type <<scserv-type-set>>, mais en indiquant la valeur de quelle étape je veux définir.

----
- if: "${editeur-id} == ''"
  id: 'affectation-editeur'
  type: set
  step: 'editeur-id'
  value: ${new-editor-id}
----

`step` contient l'identifiant de l'étape qui doit être affectée. Et l'on prend bien sûr la valeur dans l'étape `new-editor-id` dans laquelle elle a été définie.

BRAVO ! Vous venez d'accomplir déjà un gros morceau ! Nous avons choisi la maison d'édition en en définissant une nouvelle. Mais le chemin est encore long avant de voir le manuscrit partir. Dites-vous simplement que ce temps que vous passez sera _très vite_ rattrapé chaque fois que vous aurez un envoi à effectuer.

Maintenant que nous avons l'identifiant de l'éditeur, nous pouvons créer son dossier, étape que nous avons déjà implémentée : 

----
- id: creation-du-dossier-envoi
  type: 'create-folder'
  path: "./envois/${editeur-id}"
----

L'étape suivante, celle qui récupère le manuscrit, a déjà été codée aussi : 

----
- id: 'manuscrit-path'
  type: 'get-project-data'
----

Son type <<scserv-type-get-project-data>> permet de récupérer une valeur dans le projet, ici le chemin d'accès au manuscrit à transmettre.

Le souci, c'est que la première fois, cette propriété n'est pas définie pour le projet. Il faut donc en tenir compte, en sachant qu'une propriété non définie va retourner `null`. Il faut donc, après cette étape, avoir celle-ci :

----
- if: "${manuscrit-path} = null"
  id: 'selection-manuscrit'
  type: 'select-file'
  title: "Choix du manuscrit"
  q: "Choisir le manuscrit à envoyer dans le Finder puis “OK”."
----

Ici, le type <<scserv-type-select-file>> (sélection de fichier) nous permet de choisir un fichier dans le Finder. Nous allons choisir le manuscrit. Et l'étape suivante permettra d'enregistrer ce manuscrit comme donnée de projet ; nous n'aurons plus à le préciser.

NOTE: Lorsque le manuscrit changera, s'il a changé de nom (s'il est versionné par exemple), on pourra utiliser la <<project-remove-data>>.

----
- if: "${manuscrit-path} = null"
  id:   set-manuscrit-path
  type: set-project-data
  project_key: manuscrit-path
  value: "${selection-manuscrit}"
  set:  manuscript-path
----

Le type <<scserv-type-set-project-data>> permet d'enregistrer la propriété de clé `project_key` (`manuscrit-path` ici) avec la valeur de `${selection-manuscrit}`, l'étape précédente.

Le paramètre `set`, ici, va nous permettre de gagner une étape. En même temps qu'il définit la propriété du projet, il permet de définir la valeur de l'étape de l'identifiant donné, ici `manuscrit-path`.

Donc, après cette étape, notre "${selection-manuscrit}" est renseigné.

Maintenant qu'on a le manuscript, on peut procéder à la copie : 

----
- id: 'duplication-manuscrit'
  type: 'copy-file'
  source: "${manuscrit-path}"
  dest: "./envois/${editeur-id}"
----

Pour le type <<scserv-type-copy-file>>, comme nous l'avons vu, il faut définir simplement `source` et `dest`.

Pour la suite — la création du fichier avec les informations — nous devons avoir la donnée complète de l'éditeur ; rappelons-nous que si nous n'avons pas créé de nouvel éditeur, nous avons seulement son identifiant (`id`). Pour ce faire, nous allons utiliser le type <<scserv-type-get-data>>.

----
- id: 'data-editor'
  type: 'get-data'
  path: "${editors-data}"
  data_id:  "${editeur-id}"
----

Pour ce type, nous devons préciser le chemin d'accès à la base des données (qui peut-être un fichier YAML, CSV ou même une base SQlite) dans la propriété `path`. Remarquez qu'à nouveau nous utilisons la variable `${editors-data}` et pas le chemin explicite, qui peut changer.

Le fichier indiqué pourrait ne contenir que la donnée que nous voulons, nous n'aurions alors pas besoin de `data_id`. Mais en l'occurence, ce fichier contient TOUTES les informations sur TOUS les éditeurs que nous avons, docn nous devons préciser quel est l'identifiant (propriété `id` dans les données) de la donnée précise que nous attendons. Nous l'indiquons avec `data_id`. Elle correspond bien entendu à l'identifiant de l'éditeur.

Nous pouvons à présent créer le fichier d'information grâce au type <<scserv-type-create-file>> :

----
- id:     'fichier-info-editeur'
  type:   'create-file'
  content: "${data-editor}.adresse\n\n${data-editor}.phone"
  path:   "./envois/${editeur-id}/infos.md"
----

Ici, le chemin peut être mis _en dur_ puisqu'il ne sera utilisé qu'ici.

Comme nous l'avons déjà vu, nous devons demander quand l'envoi aura lieu : 

----
- id: 'date-histo'
  type: select
  title: "Date de l'envoi"
  q: "Faut-il ajouter cet envoi à  l'historique des envois ? Et si oui, quelle date faut-il indiquer ?"
  create: 'Autre date…'
  values: [['today', 'Aujourd’hui'], ['demain', "Demain"], ['non', 'Pas encore']]
----

Si une autre date doit être choisie (bouton "Autre date…") nous devons la définir : 

----
- if: "${date-histo} == ''"
  id: 'date-custom'
  type: string
  title: "Date de l'envoi"
  q: "À quelle date doit être envoyé ce manuscrit ? (JJ MM)"
  set: date-histo
----

Vous êtes normalement tout à fait en mesure maintenant de comprendre toute cette étape conditionnelle.

Rappelez-vous le paramètre `set` qui permet de définir aussitôt la valeur de l'étape `date-histo`. Nous n'avons pas à utiliser une étape juste pour l'affecter (j'adore ce genre de propriété).

Mais ici, avant de renseigner l'historique des envois, nous avons quand même un petit problème… Pour le moment, la date (`${date-histo}`) a possiblement une de ces valeurs : 

- "demain"
- "today"
- "05 08"

À part la dernière — et encore —, ça ne sera pas très expressif dans l'historique… Il nous faut donc pouvoir convertir cette valeur en vraie valeur significative.

Nous utilisons pour ça l'étape conditionnelle de type <<scserv-type-translate>> :

----
- if: "${date-histo} ≠ non"
  id:     date-to-real-date
  type:   translate
  step:   date-histo
  format: '%J %_M %Y'
----

Ici, le paramètre `step` (étape) est ce que l'on appelle un _getter_ et un _setter_, c'est-à-dire qu'il va en même temps servir à récupérer la valeur (ce sera celle de l'étape `date-histo`) et à la redéfinir avec la bonne valeur. Le format, quant à lui, permet de dire quelle forme doit avoir la donnée résultante. Ici, elle devra resembler à "5 aout 2026" (_savez-vous qu'il n'y a plus de circonflexe à "aout" ?_). Pour les valeurs “translatable” et les formats, cf. <<scserv-translate-markers-and-formats, la description des marqueurs et des formats>>.

Il ne nous reste plus qu'à enregistrer une ligne d'historique dans le fichier :

----
- if: "${date-histo} ≠ non"
  id: 'add-envoi-to-historique'
  type: 'add-to-file'
  before: "\n-"
  path: "./envois/_HISTORIQUE_.md"
  content: "- ${date-histo} Envoi aux éditions ${data-editor}.name\n"
----

Le type <<scserv-type-add-to-file>> se sert ici de `content` pour définir le contenu à injecter dans le fichier de chemin `path` en le plaçant avant (`before`) un retour chariot suivi d'un tiret, comprendre : le dernier envoi. La ligne ajoutée ressemblera à : 

----
- 5 aout 2026 Envoi aux éditions Gallimard.
----

… suivie d'un retour chariot.

Noter pour finir que l'étape ne sera jouée que si une date avait été fixée ou choisie.

BRAVO ! Vous êtes parvenu(e) au bout de ce tutoriel qui vous a permis, je l'espère, de mesurer tout le potentiel de ces _scripts-services_.

La version complète est présentée ci-dessous :

----
---
- id: editors-data
  type: set
  value: "./envois/editeurs.yaml" 

- id:     editeur-id
  type:   select
  values: "${editors-data}"
  create: "Nouvel éditeur…"
  key_value: id
  key_title: name
  title: "Choix de la maison d’édition"
  q: "Choisir un éditeur dans la liste ou en introduire un nouveau."

- if: "${editeur-id} = ''"
#  id: "new-editeur-id"
  type: string
  title: "Nouvel éditeur"
  q: "Identifiant (ascii) du nouvel éditeur :"

- if: "${editeur-id} = ''"
  id: "new-editeur-name"
  type: string
  title: "Nouvel éditeur"
  q: "Nom du nouvel éditeur :"

- if: "${editeur-id} = ''"
  id: "new-editeur-adresse"
  type: text
  title: "Nouvel éditeur"
  q: "Adresse physique du nouvel éditeur :"

- if: "${editeur-id} = ''"
  id: new-editeur-phone
  type: phone
  title: "Nouvel éditeur"
  q: "Numéro de téléphone du nouvel éditeur :"

## Pour enregistrer l'éditeur
- if: "${editeur-id} = ''"
  id: 'enregistrement-editeur'
  type: "save-data"
  path: "${editors-data}"
  prefix: 'new-editeur'
  keys: ['id', 'name', 'adresse', 'phone']
  
- if: "${editeur-id} == ''"
  id: 'affectation-editeur'
  type: set
  step: 'editeur-id'
  value: ${editeur-id-id}
  
- id: creation-du-dossier-envoi
  type: 'create-folder'
  path: "./envois/${editeur-id}"
  
- id: 'manuscrit-path'
  type: 'get-project-data'
  
- if: "${manuscrit-path} = null"
  id: 'selection-manuscrit'
  type: 'select-file'
  title: "Choix du manuscrit"
  q: "Choisir le manuscrit à envoyer dans le Finder puis “OK”."

- if: "${manuscrit-path} = null"
  id:   set-manuscrit-path
  type: set-project-data
  project_key: manuscrit-path
  value: "${selection-manuscrit}"
  set:  manuscript-path

- id: 'duplication-manuscrit'
  type: 'copy-file'
  source: "${manuscrit-path}"
  dest: "./envois/${editeur-id}"

- id: 'data-editor'
  type: 'get-data'
  path: "${editors-data}"
  data_id:  "${editeur-id}"
  
- id: 'fichier-info-editeur'
  type: 'create-file'
  content: "${data-editor}.adresse\n\n${data-editor}.phone"
  path:   "./envois/${editeur-id}/infos.md"

# Demander s'il faut ajouter à l'historique
- id: 'date-histo'
  type: select
  title: "Date de l'envoi"
  q: "Faut-il ajouter cet envoi à  l'historique des envois ? Et si oui, quelle date faut-il indiquer ?"
  create: 'Autre date…'
  values: [['today', 'Aujourd’hui'], ['demain', "Demain"], ['non', 'Pas encore']]

- if: "${date-histo} == ''"
  id: 'date-custom'
  type: string
  title: "Date de l'envoi"
  q: "À quelle date doit être envoyé ce manuscrit ?"
  set: date-histo

- if: "${date-histo} == ''"
  id:     date-mark-to-real-date
  type:   translate
  step:   date-histo # getter et setter
  format: '%J %_M %Y'

# Ajouter à l'historique s'il le faut
- if: "${date-histo} ≠ non"
  id: 'add-envoi-to-historique'
  type: 'add-to-file'
  before: "\n-"
  path: "./envois/_HISTORIQUE_.md"
  content: "- ${date-histo} Envoi aux éditions ${data-editor}.name\n"
----


---

=== Erreurs classiques ===

Vous trouverez dans cette partie une liste des erreurs classique lorsqu'on établit ses étapes.

|====
| **Manifestation** | **Erreur** 
| Signalement d'erreur    | Étape définie sans `id`.
| Signalement d'erreur    | Étape définie avec un `id` existant.
|====

[[scserv-common-params, paramètres communs]]
=== Paramètres communs à tous les types ===

[cols="1,4"]
|====
| `if`        | Pour une <<conditional-step>>.
| `id`        | Une étape toi toujours avec un identifiant, unique, contenant seulement des minuscule, des chiffres et des tirets.
| `type`      | Une étape doit toujours définir <<script-service-types, un type>>
| `q`         | Le message dans une boite de dialogue, en fonction du type attendu.
| `title`     | Le titre de la boite de dialogue, en fonction du type attendu.
| `name`      | Le nom de l'étape, mais ne sert pas beaucoup.
| `set`       | L'identifiant de l'étape à laquelle on doit donner la valeur de cette étape. 
                Voir par exemple l'utilisation dans <<scserv-vars-affectation-complexe>>.
| `transform` | Pour transformer la valeur en nombre, flottan, booléen, etc. +
                Les valeurs actuelles sont `valid-id`, `date`, `integer`, `float` ou `boolean`. +
                Les types `date` ont besoin de `format` pour définir leur format.
| `format`    | Format de transformation pour les valeurs qui en ont besoin. 
|====

include:badfile/to/seee[]

[[scserv-param-transform, transformation des valeurs]]
==== `Transform`, transformation des valeurs ====

Le paramètre `transform` permet de transformer les valeurs affectées aux étapes. Il peut avoir ces valeurs :

[cols="1,3,1"]
|====
| **Valeur transform**  | **Effet**                             | **Exemples
| `integer`, `entier`   | Transforme en entier.                 | "12" → 12
| `float`, `flottant`   | Transforme en nombre à virgule.       | "1,23" → 1.23
| `boolean`             | Transforme en booléen.                | "true" → true
| `valid-id`            | Transforme en un identifiant valide.  | "Ça c'est l'été → "ca-cest-lete"

| `date`                
| Prend une date "aaaa/mm/jj" et la met en forme (cf. <<scserv-data-formats>>).      
| "25/07/2026" → "25 juillet"

|====

[[conditional-step, étape conditionelle]]
=== Étape conditionnelle ===

On utile le paramètre `if` pour définir une étape conditionnelle.

La valeur de `if` doit alors être composée de 3 expressions séparées par une espace, la première étant la valeur a comparée, la 3^e^ la valeur de comparaison et la 2^e^ l'opérateur.

----
if: "expression operateur attendu"
----

`expression` est le plus souvent un identifiant d'étape exprimé par `${<id etape>}`. On prendra alors la valeur de cette étape pour la comparer à `expected`.

`operateur` peut être `==` ou `=`, `!=` ou `≠`, `>`, `<`.

`attendu` peut-être n'importe quelle valeur, en sachant que "null", "undefined", "empty" seront évalués. +
Quand le type est `select` et que `create` est à true (ou nom du bouton "Autre…"), autorisant la création d'une nouvelle valeur, `expected` doit alors être ''. Par exemple : 

----
- id: 'value-selected-or-created'
  name: 'valeur à sélectionner ou créer'
  type: 'select'
  create: true
  
- if: "${value-selected-or-created} == ''
  type: 'string'
  title: "Nouvelle valeur
  q: "Donnez la nouvelle valeur.
  
----


[[evaluate, évaluation]]
=== Contenu évaluable ===

Dans les étapes, un contenu _évaluable_ est un contenu qui se sert de la valeur d'une autre étape pour être défini.

Ce contenu s'indique par :

----
${step-id}          # Valeur de l'étape d'id +step-id+
${step-id}[prop]    # Si la valeur de l'étape *step-id+ est un objet, on
                    # prend la propriété +prop+ de cet objet.
${step-id}.prop     # Idem, sous une autre forme
----

Par exemple, on récupère un dossier et on s'en sert ensuite dans les étapes suivantes :

----
---
# On demande à l'utilisateur de choisir un dossier
- id: 'dossier'
  type: 'choose-folder'
  q: "Choisissez le dossier puis “OK”."

# On crée un fichier dans ce dossier.
- id: 'un-fichier-dans-le-dossier'
  type: 'add-to-file'
  # Le fichier estimé dans le dossier
  path: "${dossier}/mon_fichier.md"
  # Le contenu aussi peut s'en servir
  content: "Le contenu de mon fichier dans le dossier ${dossier}.

----

---

[[script-service-types, les types d'étape]]
=== Les types d'étapes (step) ===

_Dans cette longue partie nous allons voir et étudier tous les types d'étapes, donc les types de services utilisables dans les scripts-services._

[[scserv-type-add-to-file, `add-to-file`]]
==== Add-to-file ====

Ce type d'étape permet d'ajouter du contenu à un fichier.

----
---
- id: 'id-etape'
  type: 'add-to-file'
  path: "/chemin/vers/fichier
  content: ""
  after: "..."
  before: "..."
  where: [{after:...}, {before:...}, ...]
----

[cols="1,1,4"]
|====
| `path`    2+| Chemin d'accès au fichier
|             | Chemin absolu     | Aucune substitution nécessaire
|             | Chemin relatif    | Doit se trouver dans le dossier du projet et commencer par "./"
|             | Chemin évaluable  | Se sert de la valeur d'autres étapes
| `content` 2+| Le contenu à écrire dans le fichier. Il peut être brut ou <<evaluate, évaluable>>
| `after`   2+| Indique après quoi il faut mettre le contenu.
|             | String    | Ça peut être l'expression en chaine, p.e. "ce mot"
|             | Exp. reg. | Ou une expression régulière. P.e. "(?!un ) voisin", pour mettre après "le voisin" mais pas "un voisin). Ces expressions demande de l'expérience.
| `before`  2+| Indique avant quoi il faut mettre le contenu. Mêmes formats que pour `after`.
| `where`   2+| Alors que `after` et `before` ne permettent qu'une localisation à un paramètre, `where` permet de définir très précisément où mettre le contenu. Mais cette définition est très sensible.
|           2+| Voilà un exemple (absurde mais simple) : nous voulons ajouter ", cuisine" dans le contenu d'un fichier qui est pour le moment : "Je dois mettre au grenier un mot entre chambre et grenier." +
Nous utilisons pour ce faire : `where = [{after: "chambre"}, {before: " et grenier"}]
|           2+| De façon plus réaliste, sur cette base, on peut imaginer que le fichier contient des balises comme par exemple "/* -- debut data -- */" et "/* -- fin data -- */". Pour ajouter une donnée, on peut donc faire : +
`where = [{after: "/* -- debut data -- */\n"}, {before: "\n/* -- fin data -- */"}] +
Noter les retours de chariot marqués par "\n".
|====


[[scserv-type-save-data, `save-data`]]
==== save-data ====

Enregistrement de données. Permet d'enregistrer une donnée à la volée.

[cols="1,1,4"]
|====
| `type`    2+| `save-data`
| `id`      2+| Identifiant de l'étape.
| `keys`    2+| Les valeurs à enregistrer ou les identifiants
|             | valeurs brutes | Sans `prefix` les valeurs sont des valeurs brutes
|             | avec `prefix`  | Les clés d'un objet à reconstituer qui serviront aussi à obtenir les valeurs depuis les étapes d'identifiant `<prefix>-<key>`
| `prefix`  2+| Préfixe à utiliser pour rassembler
|====

Voir l'<<scserv-exemple-save-book>>.


[[scserv-type-set, `set`]]
==== Set ====

Permet de **définir explicitement le `step.value` d'une étape** ou de l'étape courante (pour définir une variable utile sur tout le service). Cela arrive par exemple lorsque pour un `select` on peut créer une nouvelle valeur.

[cols="1,1,4"]
|====
| `type`      2+| `set`
| `id`        2+| Identifiant obligatoire
| `step`      2+| Identifiant de l'étape dont il faut définir la valeur +
Si non défini, c'est l'étape elle-même dont on définira la valeur
| `value`     2+| Valeur à donner à `value` de l'étape
|>          soit| Valeur explicite | Donnée telle quelle 
|>          soit| Valeur d'étape   | ${<id etape>}
|====

[[scserv-type-select-file, `select-file`]]
==== Sélection d'un fichier ====

[cols="1,5"]
|====
| `type`    | `select-file`
|====


[[scserv-type-create-file, `create-file`]]
==== Création d'un fichier ====

[cols="1,5"]
|====
| `type`    | `create-file`
|====


[[scserv-type-translate, `translate`]]
==== Translate ====


Permet de transposer une valeur _par marqueur_ en vrai marqueur. L'exemple type de ces marques est la date `today` ou `tomorrow` qui sont automatiquement transposé en leur valeur réelle.

[cols="1,5"]
|====
| `type`    | `translate`
|====

----
---
- id: "id-de-step"
  type: translate
  value: "<valeur>"   # le marqueur (p.e. 'today', 'date+4'…)
  step: "<id step>"   # pour la prendre et la remettre dans l'étape
  format: "<format résultat optionnel>"
----

Si `step` est utilisé, c'est sa valeur qui est prise et remplacée. Noter qu'alors ce `step` remplace en même temps le paramètres `valeur` et `set`. La formule : 

----
- id: transformation
  type: translate
  step: la-date
  format: '%J %_M
----

… est équivalent à :

----
- id: transformation
  type: translate
  value: "${la-date}"
  set: la-date
  format: '%J %_M
----

[[scserv-translate-markers-and-formats]]
**Liste des marqueurs existants**

[cols="1,1,5"]
|====
| **Marque** 2+| **Valeur résulat**
| `today`     2+| Date d'aujourd'hui
|               | `format` | Permet de définir le format (cf. <<scserv-data-formats>>)
| `tomorrow`  2+| Date de demain
|               | `format`  | Même chose que pour `today`
| `date+<x>`  2+| Date dans le futur, `<x>` jours après aujourd'hui
|               | `format`  | Même chose que pour `today`
| `date-<x>`  2+| Date dans le passé, `<x>` jours avant aujourd'hui
|               | `format`  | Même chose que pour `today`
|====

[[scserv-data-formats, les formats de date]]
===== Les Formats de date =====

Les formats de date, utilisés pour <<scserv-param-transform>> ou le type <<scserv-type-translate>>, se définissent simplement par une chaine contenant des marqueurs qui seront remplacés par le valeur par rapport à la date fournie. Par exemple, dans la chaine `"%J %_M"`, `%J` est un marqueur qui sera remplacé par le jour de la date (le 12 si nous sommes les 12 février 2026) et `%_M` est un autre marqueur qui ser remplacé par le mois en version nom ("février" pour la même date).

**Liste des marqueurs**

[cols="1,4,1"]
|====
| **Marqueur**    | **Explication**                       | **Exemples**
| `%J`            | Le jour de la date                    | "1" ou "12"
| `%JJ`           | Le jour mais toujours sur 2 chiffres  | "01" ou "12"
| `%M`            | Le mois de la date                    | "02" ou "11"
| `%_M`           | Le nom du mois de la date             | "février"
| `%Y`            | L'année en 4 chiffres                 | "2026
| `%YY`           | L'année en 2 chiffres                 | "26"
| `%H`            | L'heure, en 1 ou 2 chiffres           | "5"
| `%m`            | Les minutes, en 2 chiffres            | "03"
| `%S`            | Les secondes en 2 chiffres            | "06"
|====

Si nous sommes le 25 juillet 2026 et que l'utilisateur choisit "Demain" pour l'étape suivante : 

----
---
- id: date-chosen
  type: select
  values:[['today', "Aujourd'hui"],['demain', "Demain"]]
  q: "Quelle date choisissez-vous ?"

- id: la-date
  type: translate
  value: "${date-chosen}"
  transform: date
  format: "%_M, %Y le %J"
----

… alors la valeur de "${la-date}" sera mise à "juillet, 2026 le 26"

[[scserv-type-select, `select`]]
==== Select ====

[cols="1,1,2"]
|====
| `id`      2+| Identifiant obligatoire
| `type`    2+| **`select`**
| `create`  2+| `true` ou le nom du bouton "Nouveau…" si on doit pouvoir créer une nouvelle valeur +
                Ça donne la valeur 'autre' à cette étape (cf. la suite).
| `values`  2+| Les valeurs parmi lesquelles ont peut choisir
|       soit  | string          | le chemin à un fichier contenant les valeurs +
La valeur sera évaluée, donc peut-être définie par "${<id étape>}"
|>      soit  | array of string | Liste de valeurs simples (['poire', 'melon'])
|>      soit  | array of array  | Liste de doubles valeurs [[value, title], ...] 
|====

Si _`create`_ est true (ou nom du bouton "Autre…"), on peut créer une valeur de toute pièce. Cette création se fait, en toute logique, au cours des étapes suivante. Ces étapes de définition vont toutes commencer par :

----
- if: "${<identifiant étape>} = ''"
----

Plusieurs étapes de ce type peuvent s'enchainer pour obtenir toutes les valeurs pour le type de données fournie.

TIP: Cette valeur est souvent réaffectée à l'étape `select` grâce à un type `set`. Voilà la séquence classique :

----
---
- id: 'le-choix'
  type: select
  values: [1, 2, 3]
  q: "Choisissez un chiffre
  create: "Autre chiffre…" # pour permettre de choisir un autre chiffre

# Comme le choix "Autre…" a été choisi, on propose
# un dialogue pour entrer une autre valeur
# et, grâce à `set`, la donner à l'autre étape
- if: "${le-choix} == ''"
  id: 'autre-chiffre'
  type: string
  q: "Quel autre chiffre ?"
  set: le-choix
  transform: integer # tranformé en nombre

# À partir d'ici, l'étape ${le-choix} contient la valeur voulue,
# qu'elle est été prise dans le menu ou définie explicitement.

----

[[scserv-type-get-data, `get-data`]]
==== Données dans un fichier ====

On peut tirer des données d'un grand nombre de fichiers. La seule exigence est que la donnée remontée ait le même type que la donnée attendue (string, array, array de strings, etc.).

[cols="1,4"]
|====
| `type` | `get-data`
| `path` | Chemin d'accès au fichier contenant les données (évaluable)
| `data_id`  | Si précisé, c'est la clé à prendre, qui deviendra la valeur de l'étape. +
Si non précisé, c'est la liste des objets qui deviendra la valeur de l'étape.
|====

Cela concerne donc en tout premier lieu les fichiers YAML, JSON et CSV, mais on peut également trouver tout fichier éditable (ruby, bash, python…) qui pourra retourner une donnée de ce type. Mais dans ce cas, il est impératif que ce fichier soit EXÉCUTABLE (`chmod +x fichier`) et qu'il retourne un données ÉVALUABLE PAR JSON, sauf si c'est une valeur scalaire (string, integer…).


Deux sortes de données peuvent être remontées :

- une table (dict) dont une clé primaire correspondra à `key`,
- une liste d'objet (array) qui devra contenir un élément répondant à `id = key`.

_En réalité, je pense qu'on peut imaginer tout autre type de valeur aussi, puisque `key` peut ne pas être défini._

[[scserv-data-create-complex]]
==== Création d'un objet complexe ====

La force des scripts-services est de pouvoir construire des objets complexes (avec plusieurs paramètres) à l'aide d'étapes successives pour pouvoir les enregistrer ensuite dans un fichier. 

[[scserv-exemple-save-book, exemple d’enregistrement d'un livre]]
Nous présentons ci-dessous l'enregistrement d'un livre dans un fichier qui les liste.

----
# Définition préalable du chemin d'accès aux données du livre,
# pour ne pas avoir à les répéter (et pouvoir les modifier 
# facilement)
- id: books-file
  type: set
  value: "./data/livres.yaml"
  
# Demande du livre qui appartient peut-être à la liste existante
- id: livre-id
  q: "Sélectionnez le livre à imprimer"
  select: "${books-file}"
  create: "Nouveau livre…" # pour en créer un nouveau

- if: "${livre-id} = ''"  # <= l'user a cliqué sur "Nouveau livre…"
  id: newlivre-titre   # id choisi avec soin (prefix-key)
  type: string
  q: "Titre du nouveau livre"

# Étape qui va tranformer le titre en identifiant valide
- if: "${livre-id} = ''"
  id: newlivre-id
  value: "${newlivre-titre}"
  transform: valid-id

- if: "${livre-id} = ''"
  id: newlivre-auteur
  q: "Auteur du livre :"
  type: string

- if: "${livre-id} = ''"
  id: newlivre-annee
  q: "Année de publication du livre :"
  type: string
  transform: integer

- if: "${livre-id} = ''"
  id: newlivre-resume
  q: "Résumé du livre :"
  type: text

# ... On pourrait ajouter encore des propriétés
    
# Cette étape va mettre dans ${new-book} l'objet du nouveau
# livre, qui pourra ensuite être enregistré
- if: "${livre-id} = ''"
  id: new-book
  type: save-data
  prefix: newlivre      # préfixe des étapes de définition
  keys: ['titre', 'id', 'resume', 'auteur', 'annee']
  path: "${books-file}"  # L'objet sera placé dans ce fichier
  
# Il reste enfin à définir ${livre-id} qui sera utilisé par
# la suite
- if: "${livre-id} = ''"
  id: define-livre-id
  type: set
  step: livre-id
  value: "${newlivre-id}"
  
  
# À partir d'ici, on peut utiliser ${livre-id} pour obtenir
# l'identifiant du livre.

# On charge les données du livre
- id: book-data
  type: get-data
  path: "${books-file}"
  data_id:  "${livre-id}" 
----


[[scserv-type-set-project-data, `set-project-data`]]
==== Set Project Data ====

Type d'étape qui permet de définir une donnée de projet.

[cols="1,4"]
|====
| `type` | `get-project-data`
| `id` | Identifiant.
| `project_key` | La clé dans les extra-données du projet.
| `value`       | La valeur à donner à cette clé. Elle vient, normalement, d'une autre étape ayant permis de la définir. Voir la <<sequence-project-data>>.
|====

[[scserv-type-get-project-data, `get-project-data`]]
==== Get Project Data ====

Type d'étape qui permet de récupérer une donnée de projet.

[cols="1,4"]
|====
| `type` | `get-project-data`
| `id` | Identifiant. Mais pour ce type d'étape, il est particulier : il doit porter le nom de la donnée du projet, impérativement, pour pouvoir être redéfini si la donnée manque.
| `project_key` | La clé dans les extra-données du projet.
|====

Voir la <<sequence-project-data>>.

[[sequence-project-data]]
**Exemple de séquence de définition de donnée de projet**

----
---
# On essaie de prendre le chemin au manuscrit
# dans les données du projet.
- id: 'manuscrit-path'
  type: 'get-project-data'

# Comme la donnée est nulle au départ, on va demande
# de choisir le manuscrit.
- if: "${manuscript-path} == null"
  id: "definition-manuscrit"
  type: 'select-file'
  q: "Choisissez le manuscrit dans le Finder puis “OK”."
  
- if: "${manuscript-path} == null"
  id: "set-project-manuscrit"
  type: 'set-project-data'
  project_key: 'manuscrit-path'  # la clé
  value: ${definition-manuscrit} # pour récupérer le path
  
- type: 'copy-file'
  source: "${manuscrit-path}"  # Aura été renseigné
----

[[scserv-type-choose-folder, `choose-folder`]]
==== Choisir un dossier ====

[cols="1,4"]
|====
| `type`    | `choose-folder`
|====

[[scserv-type-create-folder, `create-folder`]]
==== Création d'un dossier ====

[cols="1,4"]
|====
| `type`    | `create-folder`
|====


[[scserv-type-copy-file, `copy-file`]]
==== Copier d'un fichier ====

[cols="1,4"]
|====
| `type`    | `copy-file`
|====

[[scserv-type-string, `string`]]
==== Obtenir une chaine ====

[cols="1,4"]
|====
| `type`    | `string`
|====

[[scserv-type-text, `text`]]
==== Obtenir un texte ====

_Texte_, ci-dessus, signifie un texte multi-lignes.

[cols="1,4"]
|====
| `type`    | `text`
|====

[[scserv-type-phone, `phone`]]
==== Obtenir un numéro de téléphone ====

Typiquement, ces méthodes permettent surtout d'ajouter des données manquantes dans un fichier qui est utilisé dans le script-service. Au moment de l'implémentation de ce type, il servait à ajouter des fichers de maisons d'édition pour l'envoi d'un manuscrit.



[[scserv-use-variable, utilisation des variables]]
=== Utilisation des variables (valeur d’étape) ===

Dans un script-service, il est souvent utile de définir des variables et d'y faire référence.

Une variable, dans un script-service, est **une valeur d'étape**, on y fait référence par : 

----
${<id d'étape>}
----

TIP: Dans la suite, dès que nous parlerons de _**valeur d’étape**_ il faudra donc comprendre qu'il s'agit de la valeur que prend l'étape au cours de son exécution ou la valeur qu'on lui définit explicitement.

Certaines variables se définissent en une seule fois, par exemple avec le type <<scserv-type-select>> :

----
- id: 'le-nombre'
  type: select
  values: [1,2,3,4,5]
  q: "Choisissez un nombre"
----

Avec cette étape, l'user choisira un nombre de 1 à 5 et ce nombre deviendra la _valeur de l'étape `le-nombre`_ et pourra donc être utilisé avec `${le-nombre}`.

Par exemple pour une condition :

----
# Étape conditionnelle qui n'est jouée que le
# le nombre choisi est supérieur à 4
- if: "${le-nombre} > 4"
  id: etape-si-cinq
  ...
----

On peut également définir une variable explicitement grâce au type d'étape <<scserv-type-set>>. Si vous avez suivi, vous avez déjà compris que définir une variable revient à _définir la valeur d'une étape_. Si je joue :

----
- id: le-nombre
  type: set
  value: 3
----

… alors je mets explicitement la valeur de l'étape `le-nombre` à 3.

Utilisé de cette manière l'usage peut être limité, mais ça peut simplifier certaines écritures. Par exemple, si j'ai un nom assez complexe ou long, le mettre dans une variable peut être pratique :

----
- id: nom
  type: set
  value: "la Bhagavad-Gītā"
----

Je peux alors simplifier l'écriture des messages :

----
- id: version
  type: select
  q: "Quelle version de ${nom} dois-je prendre en référence ?
  values: [1,2,3]
----

[[scserv-vars-affectation-complexe]]
==== Affectation plus complexe de variables ====

Les utilisations de variable précédents restent néanmoins simplistes et correspondent plutôt à l'utilisation de _constantes_ que de véritables _variables_ dont la valeur dépend en réalité du contexte.

Voyons comment utiliser une variable, par exemple, pour obtenir le titre du projet dans lequel est utilisé le script-service courant. Cette utilisation permet la portabilité complète des scripts-services, c'est-à-dire leur utilisation dans n'importe quel projet similaire (i.e. définissant les mêmes données).

----
- id: project-name
  type: get-project-data
  key: title
----

Grâce au type de service <<scserv-type-get-project-data>>, nous pouvons obtenir la propriété `title` (titre) du projet et la stocker en valeur de l'étape. On peut ensuite l'utiliser avec `${project-name}` :

----
- id: pour-voir
  q: "Que voulez-vous faire de “${project-name}” ?"
  ...
----

> À titre de rappel, les propriétés de base de tout projet sont `title`, `id` et `path`, mais on peut en ajouter autant que l'on veut notamment grâce au type <<scserv-type-set-project-data>>.

Nous pouvons aller encore plus loin dans l'affectation des variables et c'est même une nécessité pour de nombreux scripts-service. Cela se présente typiquement lorsque l'on veut que l'utilisateur puisse donner une valeur propre, c'est-à-dire autres que celles proposées. Vous vous souvenir de l'affectation d'un nombre, tout à l'heure, à la valeur d'une variable (la valeur de l'étape). Pour que l'user puisse utiliser sa propre valeur, il suffit de définir le paramètre `create` :

----
- id: le-nombre
  type: select
  values: [1,2,3,4,5]
  q: "Choisissez un nombre"
  create: "Autre valeur…"
----

Cette fois, l'user peut cliquer sur le bouton "Autre valeur…" pour donner sa valeur personnelle. Nous savons qu'il a cliqué sur le bouton car la valeur de `${le-nombre}` sera vide. Nous la testons et lui proposons alors d'entrer sa valeur :

----
- if: "${le-nombre} = ''"
  id: autre-valeur
  type: string
  q: "Donnez votre propre valeur"
  translate: integer # pour transformer la chaine en nombre
----

Grâce à cette étape, l'user va pouvoir donner sa valeur.

Le problème, c'est qu'elle sera consignée dans `${autre-valeur}` alors que plus tard, nous en aurons besoin dans `${le-nombre}`. Pour ce faire, il nous suffit de définir le paramètre `set` avec le nom de l'autre étape : 

----
- if: "${le-nombre} = ''"
  id: autre-valeur
  type: string
  q: "Donnez votre propre valeur"
  translate: integer # pour transformer la chaine en nombre
  set: le-nombre
----

Attention de ne pas affecter la valeur trop vite ! Prenons l'exemple d'une valeur que nous devons enregistrer dans le projet, pour ne pas avoir à la définir chaque fois que nous utilisons le script-service. Nous ne pouvons pas faire : 

----
- if: "${le-nombre} = ''"
  id: autre-valeur
  type: string
  q: "Donnez votre propre valeur"
  transform: integer # pour transformer la chaine en nombre
  set: le-nombre

- if: "${le-nombre} = ''"
  id: save-nombre-in-project
  type: set-project-data
  value: "${le-nombre}"
----

Ça ne fonctionnerait pas parce qu'au moment de la ligne : 

----
- if: "${le-nombre} = ''"
----

`${le-nombre}` ne sera plus vide puisqu'il aura été défini juste au-dessus (`set: le-nombre` qui signifie "définir la valeur de l'étape `le-nombre` avec la valeur de cette étape).

Il faut donc faire : 

----
- if: "${le-nombre} = ''"
  id: autre-valeur
  type: string
  q: "Donnez votre propre valeur"
  transform: integer # pour transformer la chaine en nombre

- if: "${le-nombre} = ''"
  id: save-nombre-in-project
  type: set-project-data
  value: "${autre-valeur}"
  set: le-nombre
----

