[[scripts-services, les scripts-services]]
=== Les scripts-services ===

Les _scripts-services_ ouvrent définitivement la voie de l'infini pour définir les services d'un projet. Ils permettent de **composer soi-même un service** en exploitant toutes les ressources de l'application.

Mais tout pouvoir puissant implique des responsabilités à ses propotions.

[[script-services-steps]]
==== Une suite d'étapes ====

Un _script-service_ est un fichier YAML qui décrit les étapes du service. Concrètement, cela signifie que le fichier comporte des tirets pour délimiter chaque étape.

[code, yaml]
----
---
- name: Première étape

- name: Deuxième étape

- name: Troisième étape

# etc.
----

Pour illustrer l'explication qui va suivre, nous allons imaginer être une autrice ou un auteur et programmer un service de suivi d'envoi de manuscrits à des maisons d'édition, pour ne pas avoir à répéter un même processus des dizaines de fois, ce qui peut être pénible si l'on écrit un roman, voire plus, par an.

En apparence, ce service doit être simple : 

- création d'un dossier pour l'éditeur ou l'éditrice
- copier du manuscrit à envoyer
- création d'un fichier avec l'adresse et le téléphone de l'édition
- enregistrement d'un historique des envois, pour se souvenir de quand le manuscrit a été envoyé.

Notre fichier YAML comprendra donc ces étapes, assurément : 

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"

- name: "Copie du manuscrit envoyé"

- name: "Fichier information éditeur

- name: "Enregistrement envoi dans l'historique"

----

Noter que le `name` des étapes est optionnel, mais pour la clarté, il vaut mieux le définir.

En revanche, chaque étape doit impérativement avoir un identifiant (`ìd`). C'est une valeur ne comportant que des lettres minuscules, des chiffres, des tirets et des traits plats. Si l'identifiant contient des tirets, il doit obligatoirement être entre guillemets.

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"
  id: "creer-dossier-editeur"

- name: "Copie du manuscrit envoyé"
  id: copier_manuscrit

- name: "Fichier information éditeur
  id: informations_editeur

- name: "Enregistrement envoi dans l'historique"
  id: historique

----

==== Erreurs classiques ====

Vous trouverez dans cette partie une liste des erreurs classique lorsqu'on établit ses étapes.

|====
| **Manifestation** | **Erreur** 
|====

==== Commun à tous les types ====

[col="1,3"]
|====
| `if`        | Pour une <<conditional-step>>.
| `id`        | Une étape toi toujours avec un identifiant, unique, contenant seulement des minuscule, des chiffres et des tirets.
| `type`      | Une étape doit toujours définir <<script-service-types, un type>>
| `q`         | Le message dans une boite de dialogue, en fonction du type attendu.
| `title`     | Le titre de la boite de dialogue, en fonction du type attendu.
|====

[[conditional-step, étape conditionelle]]
===== Étape conditionnelle =====

On utile le paramètre `if` pour définir une étape conditionnelle.

La valeur de `if` doit alors être composée de 3 expressions séparées par une espace, la première étant la valeur a comparée, la 3^e^ la valeur de comparaison et la 2^e^ l'opérateur.

----
if: "expression operateur expected"
----

`expression` est le plus souvent un identifiant d'étape exprimé par `${<id etape>}`. On prendra alors la valeur de cette étape pour la comparer à `expected`.

`Expected` peut-être n'importe quelle valeur, en sachant que "null", "undefined", "empty" seront évalués. +
Quand le type est `select` et que `create` est à true, autorisant la création d'une nouvelle valeur, `expected` doit alors être '--other--'. Par exemple : 

----
- id: 'value-selected-or-created'
  name: 'valeur à sélectionner ou créer'
  type: 'select'
  create: true
  
- if: "${value-selected-or-created} == '--other--'
  type: 'string'
  title: "Nouvelle valeur
  q: "Donnez la nouvelle valeur.
  
----


[[script-service-types, les types de données]]
==== Les types de données ====

[[script-service-type-save-data]]
===== Save-data =====

Permet d'enregistrer une donnée à la volée.

[cols="1,1,2"]
|====
| `type`    2+| `save-data`
| `id`      2+| Identifiant de l'étape.
| `values`  2+| Les valeurs à enregistrer ou les identifiants
|             | valeurs brutes | Sans `prefix` les valeurs sont des valeurs brutes
|             | avec `prefix`  | Les clés d'un objet à reconstituer qui serviront aussi à obtenir les valeurs depuis les étapes d'identifiant `<prefix>-<clé>`
| `prefix`  2+| Préfixe à utiliser pour rassembler
|====

Par exemple, si l'on doit reconstituer un objet "Livre" qui possède les clés `titre`, `auteur` et `annee`, on créera les étapes id = `livre-titre`, id= `livre-auteur` et id = `livre-annee` et l'on définir les données de l'étape par :

----
---
- id: "livre-titre"
  type: "string"
  q: "Titre du livre"

- id: "livre-auteur"
  type: "string"
  q: "Auteur du livre
  
- id: "livre-annee"
  type: "integer"
  q: "Année de publication

- id: 'save-the-book'
  type: 'save-data'
  values: ['titre', 'auteur', 'annee']
  prefix: 'livre
----



[[script-service-type-set]]
===== Set =====

Permet de définir explicitement le `step.value` d'une étape ou de l'étape courante (pour définir une variable utile sur tout le service). Cela arrive par exemple lorsque pour un `select` on peut créer une nouvelle valeur.

[cols="1,1,2"]
|====
| `type`      2+| `set`
| `id`        2+| Identifiant obligatoire
| `var_step   2+| Identifiant de l'étape dont il faut définir la valeur +
Si non défini, c'est l'étape elle-même dont on définira la valeur
| `var_value  2+| Valeur à donner à `value` de l'étape
>|          soit| Valeur explicite | Donnée telle quelle 
>|          soit| Valeur d'étape   | ${<id etape>}
|====

[[script-service-type-select]]
===== Select =====

[cols="1,1,2"]
|====
| `id`      2+| Identifiant obligatoire
| `type`    2+| **`select`**
| `create`  2+| `true` si on doit pouvoir créer une nouvelle valeur +
                Ça donne la valeur 'autre' à cette étape (cf. la suite).
| `values`  2+| Les valeurs parmi lesquelles ont peut choisir
|             | string          | le chemin à un fichier contenant les valeurs +
La valeur sera évaluée, donc peut-être définie par "${<id étape>}"
>|        ou  | array of string | Liste de valeurs simples (['poire', 'melon'])
>|        ou  | array of array  | Liste de doubles valeurs [[value, title], ...] 
|====

Si _`create`_ est true, on peut créer une valeur de toute pièce. Cette création se fait, en toute logique, au cours des étapes suivante. Ces étapes de définition vont toutes commencer par :

----
- if: "${<identifiant étape>} = --other--"
----

Plusieurs étapes de ce type vont s'enchainer pour obtenir toutes les valeurs pour le type de données fournie.


create: true -- permet de dire qu'une donnée select peut être créée

[[script-service-file-values]]
==== Données dans un fichier ====

On peut tirer des données d'un grand nombre de fichiers. La seule exigence est que la donnée remontée ait le même type que la donnée attendue (string, array, array de strings, etc.).

Cela concerne donc en tout premier lieu les fichiers YAML, JSON et CSV, mais on peut également trouver tout fichier éditable (ruby, bash, python…) qui pourra retourner une donnée de ce type. Mais dans ce cas, il est impératif que ce fichier soit EXÉCUTABLE (`chmod +x fichier`) et qu'il retourne un données ÉVALUABLE PAR JSON, sauf si c'est une valeur scalaire (string, integer…).


[cols="1,3"]
|====
| `type` | `get-data`
| `base` | Chemin d'accès au fichier contenant les données (évaluable)
| `key`  | Si précisé, c'est la clé à prendre
|====

Deux sortes de données peuvent être remontées :

- une table (dict) dont une clé correspondra à `key`,
- une liste d'objet (array) qui devra contenir un élément répondant à `id = key`.

===== Set Project Data =====

Type d'étape qui permet de définir une donnée de projet.

[cols="1,3"]
|====
| `type` | `get-project-data`
| `id` | Identifiant.
| `project_key` | La clé dans les extra-données du projet.
| `value`       | La valeur à donner à cette clé. Elle vient, normalement, d'une autre étape ayant permis de la définir. Voir la <<sequence-project-data>>.
|====

===== Get Project Data =====

Type d'étape qui permet de récupérer une donnée de projet.

[cols="1,3"]
|====
| `type` | `get-project-data`
| `id` | Identifiant. Mais pour ce type d'étape, il est particulier : il doit porter le nom de la donnée du projet, impérativement, pour pouvoir être redéfini si la donnée manque.
| `project_key` | La clé dans les extra-données du projet.
|====

Voir la <<sequence-project-data>>.

[[sequence-project-data]]
**Exemple de séquence de définition de donnée de projet**

----
---
- id: 'manuscrit-path'
  type: 'get-project-data'

- if: "${manuscript-path} == null"
  id: "definition-manuscrit"
  type: 'select-file'
  
- if: "${manuscript-path} == null"
  id: "set-project-manuscrit"
  type: 'set-project-data'
  project_key: 'manuscrit-path'  # la clé
  value: ${definition-manuscrit} # pour récupérer le path
  
- type: 'copy-file'
  source: "${manuscrit-path}"  # Aura été renseigné