[[scripts-services, les scripts-services]]
== Les scripts-services ==

Les _scripts-services_ ouvrent définitivement la voie de l'infini pour définir les services d'un projet. Ils permettent de **composer soi-même un service** en exploitant toutes les ressources de l'application.

Mais tout pouvoir puissant implique des responsabilités à ses proportions, comme nous le verrons.

=== Liste complète des types assemblables ===

_Utiliser la table ci-dessous pour un accès rapide aux différents type de service_

[cols="1,3, 1"]
|====
| **Type de service**               | **Objet**                                 | **Paramètres propres**
| <<scserv-type-set>>               | Pour définir la valeur d'une étape.       | `step` + `value`
| <<scserv-type-select>>            | Sélection une valeur parmi un ensemble de
                                      valeur ou en créer une nouvelle.          | `values`, `create`
| <<scserv-type-select-file>>       | Sélection d'un fichier (dans le Finder).  | 
| <<scserv-type-create-file>>       | Création d'un fichier.                    | `path` + `content`
| <<scserv-type-add-to-file>>       | Ajout s'un contenu à un fichier.          | `after`, `before` + `where`
| <<scserv-type-get-data>>          | Obtention de données complexes 
                                      (array d'objets) depuis un fichier.       | `base`, `key`
| <<scserv-type-save-data>>         | Enregistrement de données complexes.      | `prefix`, `values`
| <<scserv-type-choose-folder>>     | Sélection d'un dossier (dans le Finder).  |
| <<scserv-type-create-folder>>     | Création d'un dossier.                    | `path`
| <<scserv-type-copy-file>>         | Copie d'un fichier.                       |
| <<scserv-type-set-project-data>>  | Pour définir une propriété pour le projet.| `step` + `value` + `project_key`
| <<scserv-type-get-project-data>>  | Pour obtenir une propriété du projet.     | `id` = prop extradata
| <<scserv-type-translate>> | Pour transformer une marqueur selon un
                              certain format.                           | `value` + `format`
| <<scserv-type-string>>            | Obtenir une valeur string.                | 
| <<scserv-type-text>>              | Obtenir une valeur texte (multi lignes).  |
| <<scserv-type-phone>>             | Obtenir un numéro de téléphone.           |
|====

[[scserv-use-variable, utilisation des variables]]
=== Utilisation des variables (valeur d’étape) ===

Dans un script-service, il est souvent utile de définir des variables et d'y faire référence.

Une variable, dans un script-service, est **une valeur d'étape**, on y fait référence par : 

----
${<id d'étape>}
----

TIP: Dans la suite, dès que nous parlerons de _**valeur d’étape**_ il faudra donc comprendre qu'il s'agit de la valeur que prend l'étape au cours de son exécution ou la valeur qu'on lui définit explicitement.

Certaines variables se définissent en une seule fois, par exemple avec le type <<scserv-type-select>> :

----
- id: 'le-nombre'
  type: select
  values: [1,2,3,4,5]
  q: "Choisissez un nombre"
----

Avec cette étape, l'user choisira un nombre de 1 à 5 et ce nombre deviendra la _valeur de l'étape `le-nombre`_ et pourra donc être utilisé avec `${le-nombre}`.

Par exemple pour une condition :

----
# Étape conditionnelle qui n'est jouée que le
# le nombre choisi est supérieur à 4
- if: "${le-nombre} > 4"
  id: etape-si-cinq
  ...
----

On peut également définir une variable explicitement grâce au type d'étape <<scserv-type-set>>. Si vous avez suivi, vous avez déjà compris que définir une variable revient à _définir la valeur d'une étape_. Si je joue :

----
- id: le-nombre
  type: set
  value: 3
----

… alors je mets explicitement la valeur de l'étape `le-nombre` à 3.

Utilisé de cette manière l'usage peut être limité, mais ça peut simplifier certaines écritures. Par exemple, si j'ai un nom assez complexe ou long, le mettre dans une variable peut être pratique :

----
- id: nom
  type: set
  value: "la Bhagavad-Gītā"
----

Je peux alors simplifier l'écriture des messages :

----
- id: version
  type: select
  q: "Quelle version de ${nom} dois-je prendre en référence ?
  values: [1,2,3]
----

[[scserv-vars-affectation-complexe]]
==== Affectation plus complexe de variables ====

Les utilisations de variable précédents restent néanmoins simplistes et correspondent plutôt à l'utilisation de _constantes_ que de véritables _variables_ dont la valeur dépend en réalité du contexte.

Voyons comment utiliser une variable, par exemple, pour obtenir le titre du projet dans lequel est utilisé le script-service courant. Cette utilisation permet la portabilité complète des scripts-services, c'est-à-dire leur utilisation dans n'importe quel projet similaire (i.e. définissant les mêmes données).

----
- id: project-name
  type: get-project-data
  key: title
----

Grâce au type de service <<scserv-type-get-project-data>>, nous pouvons obtenir la propriété `title` (titre) du projet et la stocker en valeur de l'étape. On peut ensuite l'utiliser avec `${project-name}` :

----
- id: pour-voir
  q: "Que voulez-vous faire de “${project-name}” ?"
  ...
----

> À titre de rappel, les propriétés de base de tout projet sont `title`, `id` et `path`, mais on peut en ajouter autant que l'on veut notamment grâce au type <<scserv-type-set-project-data>>.

Nous pouvons aller encore plus loin dans l'affectation des variables et c'est même une nécessité pour de nombreux scripts-service. Cela se présente typiquement lorsque l'on veut que l'utilisateur puisse donner une valeur propre, c'est-à-dire autres que celles proposées. Vous vous souvenir de l'affectation d'un nombre, tout à l'heure, à la valeur d'une variable (la valeur de l'étape). Pour que l'user puisse utiliser sa propre valeur, il suffit de définir le paramètre `create` :

----
- id: le-nombre
  type: select
  values: [1,2,3,4,5]
  q: "Choisissez un nombre"
  create: "Autre valeur…"
----

Cette fois, l'user peut cliquer sur le bouton "Autre valeur…" pour donner sa valeur personnelle. Nous savons qu'il a cliqué sur le bouton car la valeur de `${le-nombre}` sera vide. Nous la testons et lui proposons alors d'entrer sa valeur :

----
- if: "${le-nombre} = ''"
  id: autre-valeur
  type: string
  q: "Donnez votre propre valeur"
  translate: integer # pour transformer la chaine en nombre
----

Grâce à cette étape, l'user va pouvoir donner sa valeur.

Le problème, c'est qu'elle sera consignée dans `${autre-valeur}` alors que plus tard, nous en aurons besoin dans `${le-nombre}`. Pour ce faire, il nous suffit de définir le paramètre `set` avec le nom de l'autre étape : 

----
- if: "${le-nombre} = ''"
  id: autre-valeur
  type: string
  q: "Donnez votre propre valeur"
  translate: integer # pour transformer la chaine en nombre
  set: le-nombre
----

Attention de ne pas affecter la valeur trop vite ! Prenons l'exemple d'une valeur que nous devons enregistrer dans le projet, pour ne pas avoir à la définir chaque fois que nous utilisons le script-service. Nous ne pouvons pas faire : 

----
- if: "${le-nombre} = ''"
  id: autre-valeur
  type: string
  q: "Donnez votre propre valeur"
  transform: integer # pour transformer la chaine en nombre
  set: le-nombre

- if: "${le-nombre} = ''"
  id: save-nombre-in-project
  type: set-project-data
  value: "${le-nombre}"
----

Ça ne fonctionnerait pas parce qu'au moment de la ligne : 

----
- if: "${le-nombre} = ''"
----

`${le-nombre}` ne sera plus vide puisqu'il aura été défini juste au-dessus (`set: le-nombre` qui signifie "définir la valeur de l'étape `le-nombre` avec la valeur de cette étape).

Il faut donc faire : 

----
- if: "${le-nombre} = ''"
  id: autre-valeur
  type: string
  q: "Donnez votre propre valeur"
  transform: integer # pour transformer la chaine en nombre

- if: "${le-nombre} = ''"
  id: save-nombre-in-project
  type: set-project-data
  value: "${autre-valeur}"
  set: le-nombre
----


[[script-services-steps]]
=== Une suite d'étapes ===

**Un _script-service_ est un fichier YAML qui décrit la suite procédurale des étapes du service**. Concrètement, cela signifie que le fichier comporte des tirets pour délimiter chaque étape.

[code, yaml]
----
---
- name: Première étape
  id: 'etape-1

- name: Deuxième étape
  id: 'etape-2

- name: Troisième étape
  id: 'etape-3

# etc.
----

Pour illustrer l'explication qui va suivre, nous allons imaginer être une autrice ou un auteur et programmer un service de suivi d'envoi de manuscrits à des maisons d'édition, pour ne pas avoir à répéter un même processus des dizaines de fois, ce qui peut être pénible si l'on écrit un roman, voire plus, par an.

En apparence, ce service doit être simple : 

- création d'un dossier pour l'éditeur ou l'éditrice
- copier du manuscrit à envoyer
- création d'un fichier avec l'adresse et le téléphone de l'édition
- enregistrement d'un historique des envois, pour se souvenir de quand le manuscrit a été envoyé.

Notre fichier YAML comprendra donc ces étapes, assurément : 

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"

- name: "Copie du manuscrit envoyé"

- name: "Fichier information éditeur

- name: "Enregistrement envoi dans l'historique"

----

Noter que le `name` des étapes est optionnel, mais pour la clarté, il vaut mieux le définir.

En revanche, chaque étape doit impérativement avoir un identifiant (`ìd`). C'est une valeur ne comportant que des lettres minuscules, des chiffres, des tirets et des traits plats. Si l'identifiant contient des tirets, il doit obligatoirement être entre guillemets.

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"
  id: "creer-dossier-editeur"

- name: "Copie du manuscrit envoyé"
  id: copier_manuscrit

- name: "Fichier information éditeur
  id: informations_editeur

- name: "Enregistrement envoi dans l'historique"
  id: historique

----

=== Erreurs classiques ===

Vous trouverez dans cette partie une liste des erreurs classique lorsqu'on établit ses étapes.

|====
| **Manifestation** | **Erreur** 
|====

[[scserv-common-params, paramètres communs]]
=== Paramètres communs à tous les types ===

[cols="1,4"]
|====
| `if`        | Pour une <<conditional-step>>.
| `id`        | Une étape toi toujours avec un identifiant, unique, contenant seulement des minuscule, des chiffres et des tirets.
| `type`      | Une étape doit toujours définir <<script-service-types, un type>>
| `q`         | Le message dans une boite de dialogue, en fonction du type attendu.
| `title`     | Le titre de la boite de dialogue, en fonction du type attendu.
| `name`      | Le nom de l'étape, mais ne sert pas beaucoup.
| `set`       | L'identifiant de l'étape à laquelle on doit donner la valeur de cette étape. 
                Voir par exemple l'utilisation dans <<scserv-vars-affectation-complexe>>.
| `transform` | Pour transformer la valeur en nombre, flottan, booléen, etc. +
                Les valeurs actuelles sont `valid-id`, `date`, `integer`, `float` ou `boolean`. +
                Les types `date` ont besoin de `format` pour définir leur format.
| `format`    | Format de transformation pour les valeurs qui en ont besoin. 
|====

include:badfile/to/seee[]

[[scserv-param-transform, transformation des valeurs]]
==== `Transform`, transformation des valeurs ====

Le paramètre `transform` permet de transformer les valeurs affectées aux étapes. Il peut avoir ces valeurs :

[cols="1,3,1"]
|====
| **Valeur transform** | **Effet**                            | **Exemples    |
| `integer`, `entier`   | Transforme en entier.               | "12" → 12
| `float`, `flottant`   | Transforme en nombre à virgule.     | "1,23" → 1.23
| `boolean`             | Transforme en booléen.              | "true" → true
| `valid-id`            | Transforme en un identifiant valide.| "Ça c'est l'été → "ca-cest-lete"
| `date`                | Prend une date "aaaa/mm/jj" et la 
                          met en forme 
                          (cf. <<scserv-data-formats>>).      | "25/07/2026" → "25 juillet"
|====

[[conditional-step, étape conditionelle]]
=== Étape conditionnelle ===

On utile le paramètre `if` pour définir une étape conditionnelle.

La valeur de `if` doit alors être composée de 3 expressions séparées par une espace, la première étant la valeur a comparée, la 3^e^ la valeur de comparaison et la 2^e^ l'opérateur.

----
if: "expression operateur attendu"
----

`expression` est le plus souvent un identifiant d'étape exprimé par `${<id etape>}`. On prendra alors la valeur de cette étape pour la comparer à `expected`.

`operateur` peut être `==` ou `=`, `!=` ou `≠`, `>`, `<`.

`attendu` peut-être n'importe quelle valeur, en sachant que "null", "undefined", "empty" seront évalués. +
Quand le type est `select` et que `create` est à true (ou nom du bouton "Autre…"), autorisant la création d'une nouvelle valeur, `expected` doit alors être ''. Par exemple : 

----
- id: 'value-selected-or-created'
  name: 'valeur à sélectionner ou créer'
  type: 'select'
  create: true
  
- if: "${value-selected-or-created} == ''
  type: 'string'
  title: "Nouvelle valeur
  q: "Donnez la nouvelle valeur.
  
----


[[evaluate, évaluation]]
=== Contenu évaluable ===

Dans les étapes, un contenu _évaluable_ est un contenu qui se sert de la valeur d'une autre étape pour être défini.

Ce contenu s'indique par :

----
${step-id}          # Valeur de l'étape d'id +step-id+
${step-id}[prop]    # Si la valeur de l'étape *step-id+ est un objet, on
                    # prend la propriété +prop+ de cet objet.
${step-id}.prop     # Idem, sous une autre forme
----

Par exemple, on récupère un dossier et on s'en sert ensuite dans les étapes suivantes :

----
---
# On demande à l'utilisateur de choisir un dossier
- id: 'dossier'
  type: 'choose-folder'
  q: "Choisissez le dossier puis “OK”."

# On crée un fichier dans ce dossier.
- id: 'un-fichier-dans-le-dossier'
  type: 'add-to-file'
  # Le fichier estimé dans le dossier
  path: "${dossier}/mon_fichier.md"
  # Le contenu aussi peut s'en servir
  content: "Le contenu de mon fichier dans le dossier ${dossier}.

----

---

[[script-service-types, les types d'étape]]
=== Les types d'étapes (step) ===

_Dans cette longue partie nous allons voir et étudier tous les types d'étapes, donc les types de services utilisables dans les scripts-services._

[[scserv-type-add-to-file, `add-to-file`]]
==== Add-to-file ====

Ce type d'étape permet d'ajouter du contenu à un fichier.

----
---
- id: 'id-etape'
  type: 'add-to-file'
  path: "/chemin/vers/fichier
  content: ""
  after: "..."
  before: "..."
  where: [{after:...}, {before:...}, ...]
----

[cols="1,1,4"]
|====
| `path`    2+| Chemin d'accès au fichier
|             | Chemin absolu     | Aucune substitution nécessaire
|             | Chemin relatif    | Doit se trouver dans le dossier du projet et commencer par "./"
|             | Chemin évaluable  | Se sert de la valeur d'autres étapes
| `content` 2+| Le contenu à écrire dans le fichier. Il peut être brut ou <<evaluate, évaluable>>
| `after`   2+| Indique après quoi il faut mettre le contenu.
|             | String    | Ça peut être l'expression en chaine, p.e. "ce mot"
|             | Exp. reg. | Ou une expression régulière. P.e. "(?!un ) voisin", pour mettre après "le voisin" mais pas "un voisin). Ces expressions demande de l'expérience.
| `before`  2+| Indique avant quoi il faut mettre le contenu. Mêmes formats que pour `after`.
| `where`   2+| Alors que `after` et `before` ne permettent qu'une localisation à un paramètre, `where` permet de définir très précisément où mettre le contenu. Mais cette définition est très sensible.
|           2+| Voilà un exemple (absurde mais simple) : nous voulons ajouter ", cuisine" dans le contenu d'un fichier qui est pour le moment : "Je dois mettre au grenier un mot entre chambre et grenier." +
Nous utilisons pour ce faire : `where = [{after: "chambre"}, {before: " et grenier"}]
|           2+| De façon plus réaliste, sur cette base, on peut imaginer que le fichier contient des balises comme par exemple "/* -- debut data -- */" et "/* -- fin data -- */". Pour ajouter une donnée, on peut donc faire : +
`where = [{after: "/* -- debut data -- */\n"}, {before: "\n/* -- fin data -- */"}] +
Noter les retours de chariot marqués par "\n".
|====


[[scserv-type-save-data, `save-data`]]
==== save-data ====

Enregistrement de données. Permet d'enregistrer une donnée à la volée.

[cols="1,1,4"]
|====
| `type`    2+| `save-data`
| `id`      2+| Identifiant de l'étape.
| `values`  2+| Les valeurs à enregistrer ou les identifiants
|             | valeurs brutes | Sans `prefix` les valeurs sont des valeurs brutes
|             | avec `prefix`  | Les clés d'un objet à reconstituer qui serviront aussi à obtenir les valeurs depuis les étapes d'identifiant `<prefix>-<clé>`
| `prefix`  2+| Préfixe à utiliser pour rassembler
|====

Voir l'<<scserv-exemple-save-book>>.


[[scserv-type-set, `set`]]
==== Set ====

Permet de **définir explicitement le `step.value` d'une étape** ou de l'étape courante (pour définir une variable utile sur tout le service). Cela arrive par exemple lorsque pour un `select` on peut créer une nouvelle valeur.

[cols="1,1,4"]
|====
| `type`      2+| `set`
| `id`        2+| Identifiant obligatoire
| `step`      2+| Identifiant de l'étape dont il faut définir la valeur +
Si non défini, c'est l'étape elle-même dont on définira la valeur
| `value`     2+| Valeur à donner à `value` de l'étape
>|          soit| Valeur explicite | Donnée telle quelle 
>|          soit| Valeur d'étape   | ${<id etape>}
|====

[[scserv-type-select-file, `select-file`]]
==== Sélection d'un fichier ====

[cols="1,5"]
|====
| `type`    | `select-file`
|====


[[scserv-type-create-file, `create-file`]]
==== Création d'un fichier ====

[cols="1,5"]
|====
| `type`    | `create-file`
|====


[[scserv-type-translate, `translate`]]
==== Translate ====


Permet de transposer une valeur _par marqueur_ en vrai marqueur. L'exemple type de ces marques est la date `today` ou `tomorrow` qui sont automatiquement transposé en leur valeur réelle.

[cols="1,5"]
|====
| `type`    | `translate`
|====

----
---
- id: "id-de-step"
  type: translate
  value: "<valeur>"   # le marqueur (p.e. 'today', 'date+4'…)
  step: "<id step>"   # pour la prendre et la remettre dans l'étape
  format: "<format résultat optionnel>"
----

Si `step` est utilisé, c'est sa valeur qui est prise et remplacée. Noter qu'alors ce `step` remplace en même temps le paramètres `valeur` et `set`. La formule : 

----
- id: transformation
  type: translate
  step: la-date
  format: '%J %_M
----

… est équivalent à :

----
- id: transformation
  type: translate
  value: "${la-date}"
  set: la-date
  format: '%J %_M
----


**Liste des marqueurs existants**

[cols="1,1,5"]
|====
| **Marque** 2+| **Valeur résulat**
| `today`     2+| Date d'aujourd'hui
|               | `format` | Permet de définir le format (cf. <<scserv-data-formats>>)
| `tomorrow`  2+| Date de demain
|               | `format`  | Même chose que pour `today`
| `date+<x>`  2+| Date dans le futur, `<x>` jours après aujourd'hui
|               | `format`  | Même chose que pour `today`
| `date-<x>`  2+| Date dans le passé, `<x>` jours avant aujourd'hui
|               | `format`  | Même chose que pour `today`


[[scserv-data-formats, les formats de date]]
===== Les Formats de date =====

Les formats de date, utilisés pour <<scserv-param-transform>> ou le type <<scserv-type-translate>>, se définissent simplement par une chaine contenant des marqueurs qui seront remplacés par le valeur par rapport à la date fournie. Par exemple, dans la chaine `"%J %_M"`, `%J` est un marqueur qui sera remplacé par le jour de la date (le 12 si nous sommes les 12 février 2026) et `%_M` est un autre marqueur qui ser remplacé par le mois en version nom ("février" pour la même date).

**Liste des marqueurs**

[cols="1,4,1"]
|====
| **Marqueur** | **Explication** | **Exemples**
| %J            | Le jour de la date                    | "1" ou "12"
| %JJ           | Le jour mais toujours sur 2 chiffres  | "01" ou "12"
| %M            | Le mois de la date                    | "02" ou "11"
| %_M           | Le nom du mois de la date             | "février"
| %Y            | L'année en 4 chiffres                 | "2026
| %YY           | L'année en 2 chiffres                 | "26"
| %H            | L'heure, en 1 ou 2 chiffres           | "5"
| %m            | Les minutes, en 2 chiffres            | "03"
| %S            | Les secondes en 2 chiffres            | "06
|====

Si nous sommes le 25 juillet 2026 et que l'utilisateur choisit "Demain" pour l'étape suivante : 

----
---
- id: date-chosen
  type: select
  values:[['today', "Aujourd'hui"],['demain', "Demain"]]
  q: "Quelle date choisissez-vous ?"

- id: la-date
  type: translate
  value: "${date-chosen}"
  transform: date
  format: "%_M, %Y le %J"
----

… alors la valeur de "${la-date}" sera mise à "juillet, 2026 le 26"

[[scserv-type-select, `select`]]
==== Select ====

[cols="1,1,2"]
|====
| `id`      2+| Identifiant obligatoire
| `type`    2+| **`select`**
| `create`  2+| `true` ou le nom du bouton "Nouveau…" si on doit pouvoir créer une nouvelle valeur +
                Ça donne la valeur 'autre' à cette étape (cf. la suite).
| `values`  2+| Les valeurs parmi lesquelles ont peut choisir
|             | string          | le chemin à un fichier contenant les valeurs +
La valeur sera évaluée, donc peut-être définie par "${<id étape>}"
>|        ou  | array of string | Liste de valeurs simples (['poire', 'melon'])
>|        ou  | array of array  | Liste de doubles valeurs [[value, title], ...] 
|====

Si _`create`_ est true (ou nom du bouton "Autre…"), on peut créer une valeur de toute pièce. Cette création se fait, en toute logique, au cours des étapes suivante. Ces étapes de définition vont toutes commencer par :

----
- if: "${<identifiant étape>} = ''"
----

Plusieurs étapes de ce type peuvent s'enchainer pour obtenir toutes les valeurs pour le type de données fournie.

TIP: Cette valeur est souvent réaffectée à l'étape `select` grâce à un type `set`. Voilà la séquence classique :

----
---
- id: 'le-choix'
  type: select
  values: [1, 2, 3]
  q: "Choisissez un chiffre
  create: "Autre chiffre…" # pour permettre de choisir un autre chiffre

# Comme le choix "Autre…" a été choisi, on propose
# un dialogue pour entrer une autre valeur
# et, grâce à `set`, la donner à l'autre étape
- if: "${le-choix} == ''"
  id: 'autre-chiffre'
  type: string
  q: "Quel autre chiffre ?"
  set: le-choix
  transform: integer # tranformé en nombre

# À partir d'ici, l'étape ${le-choix} contient la valeur voulue,
# qu'elle est été prise dans le menu ou définie explicitement.

----

[[scserv-type-get-data, `get-data`]]
==== Données dans un fichier ====

On peut tirer des données d'un grand nombre de fichiers. La seule exigence est que la donnée remontée ait le même type que la donnée attendue (string, array, array de strings, etc.).

[cols="1,4"]
|====
| `type` | `get-data`
| `base` | Chemin d'accès au fichier contenant les données (évaluable)
| `key`  | Si précisé, c'est la clé à prendre, qui deviendra la valeur de l'étape. +
          Si non précisé, c'est la liste des objets qui deviendra la valeur de l'étape.
|====

Cela concerne donc en tout premier lieu les fichiers YAML, JSON et CSV, mais on peut également trouver tout fichier éditable (ruby, bash, python…) qui pourra retourner une donnée de ce type. Mais dans ce cas, il est impératif que ce fichier soit EXÉCUTABLE (`chmod +x fichier`) et qu'il retourne un données ÉVALUABLE PAR JSON, sauf si c'est une valeur scalaire (string, integer…).


Deux sortes de données peuvent être remontées :

- une table (dict) dont une clé primaire correspondra à `key`,
- une liste d'objet (array) qui devra contenir un élément répondant à `id = key`.

_En réalité, je pense qu'on peut imaginer tout autre type de valeur aussi, puisque `key` peut ne pas être défini._

[[scserv-data-create-complex]]
==== Création d'un objet complexe ====

La force des scripts-services est de pouvoir construire des objets complexes (avec plusieurs paramètres) à l'aide d'étapes successives pour pouvoir les enregistrer ensuite dans un fichier. 

[[scserv-exemple-save-book, exemple d’enregistrement d'un livre]]
Nous présentons ci-dessous l'enregistrement d'un livre dans un fichier qui les liste.

----
# Définition préalable du chemin d'accès aux données du livre,
# pour ne pas avoir à les répéter (et pouvoir les modifier 
# facilement)
- id: books-file
  type: set
  value: "./data/livres.yaml"
  
# Demande du livre qui appartient peut-être à la liste existante
- id: livre-id
  q: "Sélectionnez le livre à imprimer"
  select: "${books-file}"
  create: "Nouveau livre…" # pour en créer un nouveau

- if: "${livre-id} = ''"  # <= l'user a cliqué sur "Nouveau livre…"
  id: newlivre-titre   # id choisi avec soin (prefix-key)
  type: string
  q: "Titre du nouveau livre"

# Étape qui va tranformer le titre en identifiant valide
- if: "${livre-id} = ''"
  id: newlivre-id
  value: "${newlivre-titre}"
  transform: valid-id

- if: "${livre-id} = ''"
  id: newlivre-auteur
  q: "Auteur du livre :"
  type: string

- if: "${livre-id} = ''"
  id: newlivre-annee
  q: "Année de publication du livre :"
  type: string
  transform: integer

- if: "${livre-id} = ''"
  id: newlivre-resume
  q: "Résumé du livre :"
  type: text

# ... On pourrait ajouter encore des propriétés
    
# Cette étape va mettre dans ${new-book} l'objet du nouveau
# livre, qui pourra ensuite être enregistré
- if: "${livre-id} = ''"
  id: new-book
  type: save-data
  prefix: newlivre      # préfixe des étapes de définition
  values: ['titre', 'id', 'resume', 'auteur', 'annee']
  path: "${books-file}"  # L'objet sera placé dans ce fichier
  
# Il reste enfin à définir ${livre-id} qui sera utilisé par
# la suite
- if: "${livre-id} = ''"
  id: define-livre-id
  type: set
  step: livre-id
  value: "${newlivre-id}"
  
  
# À partir d'ici, on peut utiliser ${livre-id} pour obtenir
# l'identifiant du livre.

# On charge les données du livre
- id: book-data
  type: get-data
  base: "${books-file}"
  key:  "${livre-id}" 
----


[[scserv-type-set-project-data, `set-project-data`]]
==== Set Project Data ====

Type d'étape qui permet de définir une donnée de projet.

[cols="1,4"]
|====
| `type` | `get-project-data`
| `id` | Identifiant.
| `project_key` | La clé dans les extra-données du projet.
| `value`       | La valeur à donner à cette clé. Elle vient, normalement, d'une autre étape ayant permis de la définir. Voir la <<sequence-project-data>>.
|====

[[scserv-type-get-project-data, `get-project-data`]]
==== Get Project Data ====

Type d'étape qui permet de récupérer une donnée de projet.

[cols="1,4"]
|====
| `type` | `get-project-data`
| `id` | Identifiant. Mais pour ce type d'étape, il est particulier : il doit porter le nom de la donnée du projet, impérativement, pour pouvoir être redéfini si la donnée manque.
| `project_key` | La clé dans les extra-données du projet.
|====

Voir la <<sequence-project-data>>.

[[sequence-project-data]]
**Exemple de séquence de définition de donnée de projet**

----
---
# On essaie de prendre le chemin au manuscrit
# dans les données du projet.
- id: 'manuscrit-path'
  type: 'get-project-data'

# Comme la donnée est nulle au départ, on va demande
# de choisir le manuscrit.
- if: "${manuscript-path} == null"
  id: "definition-manuscrit"
  type: 'select-file'
  q: "Choisissez le manuscrit dans le Finder puis “OK”."
  
- if: "${manuscript-path} == null"
  id: "set-project-manuscrit"
  type: 'set-project-data'
  project_key: 'manuscrit-path'  # la clé
  value: ${definition-manuscrit} # pour récupérer le path
  
- type: 'copy-file'
  source: "${manuscrit-path}"  # Aura été renseigné
----

[[scserv-type-choose-folder, `choose-folder`]]
==== Choisir un dossier ====

[cols="1,4"]
|====
| `type`    | `choose-folder`
|====

[[scserv-type-create-folder, `create-folder`]]
==== Création d'un dossier ====

[cols="1,4"]
|====
| `type`    | `create-folder`
|====


[[scserv-type-copy-file, `copy-file`]]
==== Copier d'un fichier ====

[cols="1,4"]
|====
| `type`    | `copy-file`
|====

[[scserv-type-string, `string`]]
==== Obtenir une chaine ====

[cols="1,4"]
|====
| `type`    | `string`
|====

[[scserv-type-text, `text`]]
==== Obtenir un texte ====

_Texte_, ci-dessus, signifie un texte multi-lignes.

[cols="1,4"]
|====
| `type`    | `text`
|====

[[scserv-type-phone, `phone`]]
==== Obtenir un numéro de téléphone ====

Typiquement, ces méthodes permettent surtout d'ajouter des données manquantes dans un fichier qui est utilisé dans le script-service. Au moment de l'implémentation de ce type, il servait à ajouter des fichers de maisons d'édition pour l'envoi d'un manuscrit.
