[[scripts-services, les scripts-services]]
==== Les scripts-services ====

Les _scripts-services_ ouvrent définitivement la voie de l'infini pour définir les services d'un projet. Ils permettent de **composer soi-même un service** en exploitant toutes les ressources de l'application.

Mais tout pouvoir puissant implique des responsabilités à ses propotions.

[[script-services-steps]]
===== Une suite d'étapes =====

Un _script-service_ est un fichier YAML qui décrit les étapes du service. Concrètement, cela signifie que le fichier comporte des tirets pour délimiter chaque étape.

[code, yaml]
----
---
- name: Première étape

- name: Deuxième étape

- name: Troisième étape

# etc.
----

Pour illustrer l'explication qui va suivre, nous allons imaginer être une autrice ou un auteur et programmer un service de suivi d'envoi de manuscrits à des maisons d'édition, pour ne pas avoir à répéter un même processus des dizaines de fois, ce qui peut être pénible si l'on écrit un roman, voire plus, par an.

En apparence, ce service doit être simple : 

- création d'un dossier pour l'éditeur ou l'éditrice
- copier du manuscrit à envoyer
- création d'un fichier avec l'adresse et le téléphone de l'édition
- enregistrement d'un historique des envois, pour se souvenir de quand le manuscrit a été envoyé.

Notre fichier YAML comprendra donc ces étapes, assurément : 

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"

- name: "Copie du manuscrit envoyé"

- name: "Fichier information éditeur

- name: "Enregistrement envoi dans l'historique"

----

Noter que le `name` des étapes est optionnel, mais pour la clarté, il vaut mieux le définir.

En revanche, chaque étape doit impérativement avoir un identifiant (`ìd`). C'est une valeur ne comportant que des lettres minuscules, des chiffres, des tirets et des traits plats. Si l'identifiant contient des tirets, il doit obligatoirement être entre guillemets.

[code, yaml]
----
---
- name: "Création du dossier de l'éditeur"
  id: "creer-dossier-editeur"

- name: "Copie du manuscrit envoyé"
  id: copier_manuscrit

- name: "Fichier information éditeur
  id: informations_editeur

- name: "Enregistrement envoi dans l'historique"
  id: historique

----


À PLACER
Quand le type est '<type>-or-path', path peut contenir le type attendu.
Si <path> est un fichier autre que .yaml, .json ou .csv, il doit être EXÉCUTABLE et retourner un données ÉVALUABLE PAR JSON (JSON.parse en ruby).
Si le fichier n'est pas exécutable (`chmod +x fichier`) ou qu'il ne retourne pas une donnée au format JSON, une erreur sera produite.